// AUTO-GENERATED by scripts/build-films.ts — do not edit by hand.
// Your data (rating, watched, watchedOn, notes) lives in films.json; the rest
// is TMDB metadata baked in here at build time. `privateNotes` never lands in
// this file. Regenerate with: bun run scripts/build-films.ts
//
// 221 titles · generated 2026-06-23

export type TitleType =
	| 'Movie'
	| 'TV Series'
	| 'TV Mini Series'
	| 'Short'
	| 'TV Movie'
	| (string & {});

export interface Film {
	/** IMDb const, e.g. tt0166924 */
	id: string;
	title: string;
	year: number;
	type: TitleType;
	/** Personal rating, 1–10 */
	rating: number;
	/** Runtime in minutes, when known */
	runtime: number | null;
	genres: string[];
	directors: string[];
	/** TMDB poster_path, hotlinked from image.tmdb.org; null when none exists */
	posterPath: string | null;
	/** Times watched (default 1) */
	watched: number;
	/** Date watched, ISO yyyy-mm-dd */
	watchedOn: string;
	/** Public note, shown on the site */
	notes?: string;
}

export const films: Film[] = [
	{
		"id": "tt3398268",
		"title": "When Marnie Was There",
		"year": 2014,
		"type": "Movie",
		"rating": 10,
		"runtime": 103,
		"genres": [
			"Animation",
			"Drama",
			"Family",
			"Mystery"
		],
		"directors": [
			"Hiromasa Yonebayashi"
		],
		"posterPath": "/vug1dvDI1tSa60Z8qjCuUE7ntkO.jpg",
		"watched": 1,
		"watchedOn": "2021-10-24"
	},
	{
		"id": "tt0468569",
		"title": "The Dark Knight",
		"year": 2008,
		"type": "Movie",
		"rating": 10,
		"runtime": 152,
		"genres": [
			"Crime",
			"Thriller"
		],
		"directors": [
			"Christopher Nolan"
		],
		"posterPath": "/qJ2tW6WMUDux911r6m7haRef0WH.jpg",
		"watched": 2,
		"watchedOn": "2025-01-25"
	},
	{
		"id": "tt0417299",
		"title": "Avatar: The Last Airbender",
		"year": 2005,
		"type": "TV Series",
		"rating": 10,
		"runtime": 23,
		"genres": [
			"Animation",
			"Adventure",
			"Family",
			"Fantasy",
			"Action",
			"Mystery"
		],
		"directors": [],
		"posterPath": "/9RQhVb3r3mCMqYVhLoCu4EvuipP.jpg",
		"watched": 5,
		"watchedOn": "2020-12-03"
	},
	{
		"id": "tt0167260",
		"title": "The Lord of the Rings: The Return of the King",
		"year": 2003,
		"type": "Movie",
		"rating": 10,
		"runtime": 201,
		"genres": [
			"Drama",
			"Adventure",
			"Fantasy"
		],
		"directors": [
			"Peter Jackson"
		],
		"posterPath": "/rCzpDGLbOoPwLjy3OAm5NUPOTrC.jpg",
		"watched": 3,
		"watchedOn": "2021-03-23"
	},
	{
		"id": "tt0167261",
		"title": "The Lord of the Rings: The Two Towers",
		"year": 2002,
		"type": "Movie",
		"rating": 10,
		"runtime": 179,
		"genres": [
			"Drama",
			"Adventure",
			"Fantasy"
		],
		"directors": [
			"Peter Jackson"
		],
		"posterPath": "/5VTN0pR8gcqV3EPUHHfMGnJYN9L.jpg",
		"watched": 3,
		"watchedOn": "2021-03-23"
	},
	{
		"id": "tt0166924",
		"title": "Mulholland Drive",
		"year": 2001,
		"type": "Movie",
		"rating": 10,
		"runtime": 147,
		"genres": [
			"Drama",
			"Thriller",
			"Mystery"
		],
		"directors": [
			"David Lynch"
		],
		"posterPath": "/x7A59t6ySylr1L7aubOQEA480vM.jpg",
		"watched": 1,
		"watchedOn": "2025-06-26"
	},
	{
		"id": "tt0245429",
		"title": "Spirited Away",
		"year": 2001,
		"type": "Movie",
		"rating": 10,
		"runtime": 124,
		"genres": [
			"Animation",
			"Family",
			"Adventure",
			"Fantasy"
		],
		"directors": [
			"Hayao Miyazaki"
		],
		"posterPath": "/39wmItIWsg5sZMyRUHLkWBcuVCM.jpg",
		"watched": 1,
		"watchedOn": "2022-07-28"
	},
	{
		"id": "tt0120737",
		"title": "The Lord of the Rings: The Fellowship of the Ring",
		"year": 2001,
		"type": "Movie",
		"rating": 10,
		"runtime": 178,
		"genres": [
			"Drama",
			"Adventure",
			"Fantasy"
		],
		"directors": [
			"Peter Jackson"
		],
		"posterPath": "/6oom5QYQ2yQTMJIbnvbkBL9cHo6.jpg",
		"watched": 3,
		"watchedOn": "2021-03-26"
	},
	{
		"id": "tt0120663",
		"title": "Eyes Wide Shut",
		"year": 1999,
		"type": "Movie",
		"rating": 10,
		"runtime": 159,
		"genres": [
			"Mystery",
			"Drama",
			"Thriller"
		],
		"directors": [
			"Stanley Kubrick"
		],
		"posterPath": "/knEIz1eNGl5MQDbrEAVWA7iRqF9.jpg",
		"watched": 1,
		"watchedOn": "2025-06-19"
	},
	{
		"id": "tt7366338",
		"title": "Chernobyl",
		"year": 2019,
		"type": "TV Mini Series",
		"rating": 9,
		"runtime": 60,
		"genres": [
			"Drama",
			"History",
			"Thriller"
		],
		"directors": [],
		"posterPath": "/hlLXt2tOPT6RRnjiUmoxyG1LTFi.jpg",
		"watched": 1,
		"watchedOn": "2023-06-07"
	},
	{
		"id": "tt9253866",
		"title": "Our Planet",
		"year": 2019,
		"type": "TV Series",
		"rating": 9,
		"runtime": 50,
		"genres": [
			"Documentary",
			"Family"
		],
		"directors": [],
		"posterPath": "/wRSnArnQBmeUYb5GWDU595bGsBr.jpg",
		"watched": 1,
		"watchedOn": "2021-06-22"
	},
	{
		"id": "tt5363918",
		"title": "Disenchantment",
		"year": 2018,
		"type": "TV Series",
		"rating": 9,
		"runtime": 30,
		"genres": [
			"Animation",
			"Comedy",
			"Fantasy",
			"Adventure",
			"Action",
			"Horror",
			"Romance",
			"Sci-Fi"
		],
		"directors": [],
		"posterPath": "/1WynayCqKRzrl4cFZR8NOfiDwd6.jpg",
		"watched": 3,
		"watchedOn": "2025-06-17"
	},
	{
		"id": "tt1856101",
		"title": "Blade Runner 2049",
		"year": 2017,
		"type": "Movie",
		"rating": 9,
		"runtime": 164,
		"genres": [
			"Sci-Fi",
			"Thriller",
			"Action",
			"Drama",
			"Mystery"
		],
		"directors": [
			"Denis Villeneuve"
		],
		"posterPath": "/gajva2L0rPYkEWjzgFlBXCAVBE5.jpg",
		"watched": 2,
		"watchedOn": "2022-05-19"
	},
	{
		"id": "tt3783958",
		"title": "La La Land",
		"year": 2016,
		"type": "Movie",
		"rating": 9,
		"runtime": 128,
		"genres": [
			"Musical",
			"Comedy",
			"Drama",
			"Romance",
			"Music"
		],
		"directors": [
			"Damien Chazelle"
		],
		"posterPath": "/uDO8zWDhfWwoFdKS4fzkUJt0Rf0.jpg",
		"watched": 1,
		"watchedOn": "2025-06-19"
	},
	{
		"id": "tt5311514",
		"title": "Your Name.",
		"year": 2016,
		"type": "Movie",
		"rating": 9,
		"runtime": 106,
		"genres": [
			"Animation",
			"Drama",
			"Romance",
			"Fantasy"
		],
		"directors": [
			"Makoto Shinkai"
		],
		"posterPath": "/q719jXXEzOoYaps6babgKnONONX.jpg",
		"watched": 1,
		"watchedOn": "2025-06-19"
	},
	{
		"id": "tt4158110",
		"title": "Mr. Robot",
		"year": 2015,
		"type": "TV Series",
		"rating": 9,
		"runtime": 45,
		"genres": [
			"Crime",
			"Drama",
			"Thriller"
		],
		"directors": [],
		"posterPath": "/kv1nRqgebSsREnd7vdC2pSGjpLo.jpg",
		"watched": 1,
		"watchedOn": "2023-07-10"
	},
	{
		"id": "tt3718778",
		"title": "Over the Garden Wall",
		"year": 2014,
		"type": "TV Mini Series",
		"rating": 9,
		"runtime": 11,
		"genres": [
			"Animation",
			"Short",
			"Fantasy",
			"Adventure",
			"Drama",
			"Family",
			"Horror",
			"Mystery",
			"Comedy",
			"Music"
		],
		"directors": [],
		"posterPath": "/m3lU8n7WxzMecxKZcqhq5y5ESy.jpg",
		"watched": 1,
		"watchedOn": "2020-12-03"
	},
	{
		"id": "tt0993846",
		"title": "The Wolf of Wall Street",
		"year": 2013,
		"type": "Movie",
		"rating": 9,
		"runtime": 180,
		"genres": [
			"Crime",
			"Drama",
			"Biography",
			"Comedy"
		],
		"directors": [
			"Martin Scorsese"
		],
		"posterPath": "/kW9LmvYHAaS9iA0tHmZVq8hQYoq.jpg",
		"watched": 1,
		"watchedOn": "2025-06-30"
	},
	{
		"id": "tt1853728",
		"title": "Django Unchained",
		"year": 2012,
		"type": "Movie",
		"rating": 9,
		"runtime": 165,
		"genres": [
			"Western",
			"Drama"
		],
		"directors": [
			"Quentin Tarantino"
		],
		"posterPath": "/7oWY8VDWW7thTzWh3OKYRkWUlD5.jpg",
		"watched": 1,
		"watchedOn": "2025-06-26"
	},
	{
		"id": "tt0780504",
		"title": "Drive",
		"year": 2011,
		"type": "Movie",
		"rating": 9,
		"runtime": 100,
		"genres": [
			"Drama",
			"Action"
		],
		"directors": [
			"Nicolas Winding Refn"
		],
		"posterPath": "/602vevIURmpDfzbnv5Ubi6wIkQm.jpg",
		"watched": 1,
		"watchedOn": "2023-05-16"
	},
	{
		"id": "tt1305826",
		"title": "Adventure Time",
		"year": 2010,
		"type": "TV Series",
		"rating": 9,
		"runtime": 23,
		"genres": [
			"Animation",
			"Adventure",
			"Comedy",
			"Fantasy",
			"Sci-Fi",
			"Action",
			"Family"
		],
		"directors": [],
		"posterPath": "/qk3eQ8jW4opJ48gFWYUXWaMT4l.jpg",
		"watched": 1,
		"watchedOn": "2025-06-19"
	},
	{
		"id": "tt0361748",
		"title": "Inglourious Basterds",
		"year": 2009,
		"type": "Movie",
		"rating": 9,
		"runtime": 153,
		"genres": [
			"War",
			"Drama"
		],
		"directors": [
			"Quentin Tarantino"
		],
		"posterPath": "/3Gb6G2amMuKZmmCpRqM4N67s8eE.jpg",
		"watched": 1,
		"watchedOn": "2025-08-31"
	},
	{
		"id": "tt0381061",
		"title": "Casino Royale",
		"year": 2006,
		"type": "Movie",
		"rating": 9,
		"runtime": 144,
		"genres": [
			"Thriller",
			"Action",
			"Adventure"
		],
		"directors": [
			"Martin Campbell"
		],
		"posterPath": "/lMrxYKKhd4lqRzwUHAy5gcx9PSO.jpg",
		"watched": 1,
		"watchedOn": "2024-08-26"
	},
	{
		"id": "tt0206634",
		"title": "Children of Men",
		"year": 2006,
		"type": "Movie",
		"rating": 9,
		"runtime": 109,
		"genres": [
			"Thriller",
			"Drama",
			"Sci-Fi"
		],
		"directors": [
			"Alfonso Cuarón"
		],
		"posterPath": "/k9IAS4TehZFcKi4HVByxZNPfqex.jpg",
		"watched": 1,
		"watchedOn": "2025-07-05"
	},
	{
		"id": "tt0309987",
		"title": "The Dreamers",
		"year": 2003,
		"type": "Movie",
		"rating": 9,
		"runtime": 115,
		"genres": [
			"Romance",
			"Drama"
		],
		"directors": [
			"Bernardo Bertolucci"
		],
		"posterPath": "/gBb7GGaFYPu7nEUYvC8G4LaJJN1.jpg",
		"watched": 1,
		"watchedOn": "2025-06-19"
	},
	{
		"id": "tt0278238",
		"title": "Samurai Jack",
		"year": 2001,
		"type": "TV Series",
		"rating": 9,
		"runtime": 23,
		"genres": [
			"Animation",
			"Thriller",
			"Sci-Fi",
			"Drama",
			"Adventure",
			"Fantasy",
			"Action"
		],
		"directors": [],
		"posterPath": "/ddZ7Q2WZ0xAHkVXYvcEgNGFgVkw.jpg",
		"watched": 1,
		"watchedOn": "2025-06-26"
	},
	{
		"id": "tt0114369",
		"title": "Seven",
		"year": 1995,
		"type": "Movie",
		"rating": 9,
		"runtime": 127,
		"genres": [
			"Mystery",
			"Drama",
			"Crime",
			"Thriller"
		],
		"directors": [
			"David Fincher"
		],
		"posterPath": "/191nKfP0ehp3uIvWqgPbFmI4lv9.jpg",
		"watched": 1,
		"watchedOn": "2025-06-19"
	},
	{
		"id": "tt0095327",
		"title": "Grave of the Fireflies",
		"year": 1988,
		"type": "Movie",
		"rating": 9,
		"runtime": 88,
		"genres": [
			"Animation",
			"Drama",
			"War"
		],
		"directors": [
			"Isao Takahata"
		],
		"posterPath": "/k9tv1rXZbOhH7eiCk378x61kNQ1.jpg",
		"watched": 1,
		"watchedOn": "2025-06-19"
	},
	{
		"id": "tt0086250",
		"title": "Scarface",
		"year": 1983,
		"type": "Movie",
		"rating": 9,
		"runtime": 170,
		"genres": [
			"Crime",
			"Drama"
		],
		"directors": [
			"Brian De Palma"
		],
		"posterPath": "/iQ5ztdjvteGeboxtmRdXEChJOHh.jpg",
		"watched": 1,
		"watchedOn": "2025-03-10"
	},
	{
		"id": "tt37287335",
		"title": "Obsession",
		"year": 2026,
		"type": "Movie",
		"rating": 8,
		"runtime": 108,
		"genres": [
			"Horror",
			"Thriller"
		],
		"directors": [
			"Curry Barker"
		],
		"posterPath": "/bRwnj8WEKBCvmfeUNOukJPwB43K.jpg",
		"watched": 1,
		"watchedOn": "2026-06-21"
	},
	{
		"id": "tt32820897",
		"title": "Demon Slayer: Kimetsu No Yaiba Infinity Castle",
		"year": 2025,
		"type": "Movie",
		"rating": 8,
		"runtime": 155,
		"genres": [
			"Animation",
			"Action",
			"Adventure",
			"Fantasy",
			"Thriller"
		],
		"directors": [
			"Haruo Sotozaki",
			"Hikaru Kondô"
		],
		"posterPath": "/fWVSwgjpT2D78VUh6X8UBd2rorW.jpg",
		"watched": 1,
		"watchedOn": "2026-05-21"
	},
	{
		"id": "tt16311594",
		"title": "F1: The Movie",
		"year": 2025,
		"type": "Movie",
		"rating": 8,
		"runtime": 155,
		"genres": [
			"Sport",
			"Drama"
		],
		"directors": [
			"Joseph Kosinski"
		],
		"posterPath": "/9PXZIUsSDh4alB80jheWX4fhZmy.jpg",
		"watched": 1,
		"watchedOn": "2025-07-02"
	},
	{
		"id": "tt14905854",
		"title": "Hamnet",
		"year": 2025,
		"type": "Movie",
		"rating": 8,
		"runtime": 125,
		"genres": [
			"Biography",
			"Drama",
			"History",
			"Romance"
		],
		"directors": [
			"Chloé Zhao"
		],
		"posterPath": "/zIcd6yuBucRNof5t9KVuGBHIhXU.jpg",
		"watched": 1,
		"watchedOn": "2026-03-23"
	},
	{
		"id": "tt17526714",
		"title": "The Substance",
		"year": 2024,
		"type": "Movie",
		"rating": 8,
		"runtime": 141,
		"genres": [
			"Drama",
			"Horror",
			"Sci-Fi"
		],
		"directors": [
			"Coralie Fargeat"
		],
		"posterPath": "/lqoMzCcZYEFK729d6qzt349fB4o.jpg",
		"watched": 1,
		"watchedOn": "2025-02-06"
	},
	{
		"id": "tt15398776",
		"title": "Oppenheimer",
		"year": 2023,
		"type": "Movie",
		"rating": 8,
		"runtime": 180,
		"genres": [
			"Biography",
			"Drama",
			"History"
		],
		"directors": [
			"Christopher Nolan"
		],
		"posterPath": "/8Gxv8gSFCU0XGDykEGv7zR1n2ua.jpg",
		"watched": 1,
		"watchedOn": "2025-05-12"
	},
	{
		"id": "tt1877830",
		"title": "The Batman",
		"year": 2022,
		"type": "Movie",
		"rating": 8,
		"runtime": 176,
		"genres": [
			"Crime",
			"Mystery",
			"Action",
			"Drama"
		],
		"directors": [
			"Matt Reeves"
		],
		"posterPath": "/74xTEgt7R36Fpooo50r9T25onhq.jpg",
		"watched": 1,
		"watchedOn": "2025-06-19"
	},
	{
		"id": "tt14114802",
		"title": "The Outfit",
		"year": 2022,
		"type": "Movie",
		"rating": 8,
		"runtime": 105,
		"genres": [
			"Crime",
			"Drama",
			"Thriller",
			"Mystery"
		],
		"directors": [
			"Graham Moore"
		],
		"posterPath": "/lZa5EB6PVJBT5mxhgZS5ftqdAm6.jpg",
		"watched": 1,
		"watchedOn": "2022-04-08"
	},
	{
		"id": "tt1745960",
		"title": "Top Gun: Maverick",
		"year": 2022,
		"type": "Movie",
		"rating": 8,
		"runtime": 130,
		"genres": [
			"Action",
			"Drama"
		],
		"directors": [
			"Joseph Kosinski"
		],
		"posterPath": "/n0YuM4f5lvGAP6MAW2kBIzugXnc.jpg",
		"watched": 1,
		"watchedOn": "2022-06-13"
	},
	{
		"id": "tt11126994",
		"title": "Arcane",
		"year": 2021,
		"type": "TV Series",
		"rating": 8,
		"runtime": 40,
		"genres": [
			"Animation",
			"Action",
			"Adventure",
			"Drama",
			"Fantasy",
			"Sci-Fi"
		],
		"directors": [],
		"posterPath": "/abf8tHznhSvl9BAElD2cQeRr7do.jpg",
		"watched": 1,
		"watchedOn": "2025-06-19"
	},
	{
		"id": "tt16492678",
		"title": "Demon Slayer: Kimetsu no Yaiba - Tsuzumi Mansion Arc",
		"year": 2021,
		"type": "Movie",
		"rating": 8,
		"runtime": 87,
		"genres": [
			"Animation",
			"Action",
			"Fantasy"
		],
		"directors": [
			"Haruo Sotozaki"
		],
		"posterPath": "/2yiDQCDj7hlq2SwLojV9xrFkCnr.jpg",
		"watched": 1,
		"watchedOn": "2026-05-21"
	},
	{
		"id": "tt4244994",
		"title": "The Last Duel",
		"year": 2021,
		"type": "Movie",
		"rating": 8,
		"runtime": 152,
		"genres": [
			"Drama",
			"History",
			"Thriller"
		],
		"directors": [
			"Ridley Scott"
		],
		"posterPath": "/zjrJE0fpzPvX8saJXj8VNfcjBoU.jpg",
		"watched": 1,
		"watchedOn": "2021-11-02"
	},
	{
		"id": "tt11032374",
		"title": "Demon Slayer: Kimetsu no Yaiba - The Movie: Mugen Train",
		"year": 2020,
		"type": "Movie",
		"rating": 8,
		"runtime": 117,
		"genres": [
			"Animation",
			"Action",
			"Adventure",
			"Fantasy",
			"Thriller"
		],
		"directors": [
			"Haruo Sotozaki"
		],
		"posterPath": "/h8Rb9gBr48ODIwYUttZNYeMWeUU.jpg",
		"watched": 1,
		"watchedOn": "2026-05-21"
	},
	{
		"id": "tt7661390",
		"title": "Gangs of London",
		"year": 2020,
		"type": "TV Series",
		"rating": 8,
		"runtime": 60,
		"genres": [
			"Drama",
			"Action",
			"Crime",
			"Thriller",
			"War"
		],
		"directors": [],
		"posterPath": "/fVgwa6wGw9ddGM5O7mqrrwB6gHK.jpg",
		"watched": 1,
		"watchedOn": "2021-05-19"
	},
	{
		"id": "tt10048342",
		"title": "The Queen's Gambit",
		"year": 2020,
		"type": "TV Mini Series",
		"rating": 8,
		"runtime": 60,
		"genres": [
			"Drama"
		],
		"directors": [],
		"posterPath": "/zU0htwkhNvBQdVSIKB9s6hgVeFK.jpg",
		"watched": 1,
		"watchedOn": "2020-12-03"
	},
	{
		"id": "tt9335498",
		"title": "Demon Slayer: Kimetsu no Yaiba",
		"year": 2019,
		"type": "TV Series",
		"rating": 8,
		"runtime": 24,
		"genres": [
			"Animation",
			"Action",
			"Fantasy",
			"Thriller",
			"Adventure"
		],
		"directors": [],
		"posterPath": "/xUfRZu2mi8jH6SzQEJGP6tjBuYj.jpg",
		"watched": 1,
		"watchedOn": "2026-05-21"
	},
	{
		"id": "tt7216636",
		"title": "Hazbin Hotel",
		"year": 2019,
		"type": "TV Series",
		"rating": 8,
		"runtime": 32,
		"genres": [
			"Animation",
			"Musical",
			"Comedy",
			"Fantasy",
			"Drama"
		],
		"directors": [],
		"posterPath": "/aVYHMW8pdzJ9qG1OGRMKyGy9xor.jpg",
		"watched": 1,
		"watchedOn": "2021-04-06"
	},
	{
		"id": "tt7286456",
		"title": "Joker",
		"year": 2019,
		"type": "Movie",
		"rating": 8,
		"runtime": 122,
		"genres": [
			"Drama"
		],
		"directors": [
			"Todd Phillips"
		],
		"posterPath": "/udDclJoHjfjb8Ekgsd4FDteOkCU.jpg",
		"watched": 1,
		"watchedOn": "2020-12-03"
	},
	{
		"id": "tt7131622",
		"title": "Once Upon a Time in... Hollywood",
		"year": 2019,
		"type": "Movie",
		"rating": 8,
		"runtime": 161,
		"genres": [
			"Drama",
			"Comedy"
		],
		"directors": [
			"Quentin Tarantino"
		],
		"posterPath": "/8j58iEBw9pOXFD2L0nt0ZXeHviB.jpg",
		"watched": 1,
		"watchedOn": "2025-08-24"
	},
	{
		"id": "tt7767422",
		"title": "Sex Education",
		"year": 2019,
		"type": "TV Series",
		"rating": 8,
		"runtime": 60,
		"genres": [
			"Drama",
			"Comedy",
			"Romance"
		],
		"directors": [],
		"posterPath": "/bc3bmTdnoKcRuO9xdQKgAbB7Y9Z.jpg",
		"watched": 1,
		"watchedOn": "2021-09-27"
	},
	{
		"id": "tt7057496",
		"title": "Forgotten",
		"year": 2017,
		"type": "Movie",
		"rating": 8,
		"runtime": 108,
		"genres": [
			"Mystery",
			"Thriller",
			"Crime"
		],
		"directors": [
			"Jang Hang-jun"
		],
		"posterPath": "/cBgj41y1RvmW1zJCEX0uNWL0UjW.jpg",
		"watched": 1,
		"watchedOn": "2020-12-03"
	},
	{
		"id": "tt1790809",
		"title": "Pirates of the Caribbean: Dead Men Tell No Tales",
		"year": 2017,
		"type": "Movie",
		"rating": 8,
		"runtime": 129,
		"genres": [
			"Action",
			"Adventure",
			"Fantasy"
		],
		"directors": [
			"Joachim Rønning",
			"Espen Sandberg"
		],
		"posterPath": "/6lAPOAFYFWIO3SQRemEY2wInQMC.jpg",
		"watched": 1,
		"watchedOn": "2025-06-19"
	},
	{
		"id": "tt5323662",
		"title": "A Silent Voice: The Movie",
		"year": 2016,
		"type": "Movie",
		"rating": 8,
		"runtime": 130,
		"genres": [
			"Animation",
			"Drama"
		],
		"directors": [
			"Naoko Yamada"
		],
		"posterPath": "/tuFaWiqX0TXoWu7DGNcmX3UW7sT.jpg",
		"watched": 1,
		"watchedOn": "2023-05-18"
	},
	{
		"id": "tt5491994",
		"title": "Planet Earth II",
		"year": 2016,
		"type": "TV Mini Series",
		"rating": 8,
		"runtime": 50,
		"genres": [
			"Documentary",
			"Family"
		],
		"directors": [],
		"posterPath": "/5maYKYzWpE68ycxGh1luu4P2LOS.jpg",
		"watched": 1,
		"watchedOn": "2021-05-19"
	},
	{
		"id": "tt3742982",
		"title": "Akame ga Kill!",
		"year": 2014,
		"type": "TV Series",
		"rating": 8,
		"runtime": 24,
		"genres": [
			"Animation",
			"Action",
			"Comedy",
			"Drama",
			"Fantasy",
			"Thriller",
			"Horror"
		],
		"directors": [],
		"posterPath": "/rMpvMbSlPbm5QYfFem9fx2Jnttq.jpg",
		"watched": 1,
		"watchedOn": "2021-01-27"
	},
	{
		"id": "tt0816692",
		"title": "Interstellar",
		"year": 2014,
		"type": "Movie",
		"rating": 8,
		"runtime": 169,
		"genres": [
			"Sci-Fi",
			"Adventure",
			"Drama"
		],
		"directors": [
			"Christopher Nolan"
		],
		"posterPath": "/yQvGrMoipbRoddT0ZR8tPoR7NfX.jpg",
		"watched": 1,
		"watchedOn": "2025-06-19"
	},
	{
		"id": "tt2872718",
		"title": "Nightcrawler",
		"year": 2014,
		"type": "Movie",
		"rating": 8,
		"runtime": 117,
		"genres": [
			"Crime",
			"Thriller",
			"Drama"
		],
		"directors": [
			"Dan Gilroy"
		],
		"posterPath": "/j9HrX8f7GbZQm1BrBiR40uFQZSb.jpg",
		"watched": 1,
		"watchedOn": "2023-04-23"
	},
	{
		"id": "tt4839610",
		"title": "We Bare Bears",
		"year": 2014,
		"type": "TV Series",
		"rating": 8,
		"runtime": 30,
		"genres": [
			"Animation",
			"Comedy",
			"Family",
			"Fantasy",
			"Adventure"
		],
		"directors": [],
		"posterPath": "/3xWzlLZ0kAD6SkVZTekFM9lxZyP.jpg",
		"watched": 1,
		"watchedOn": "2021-07-04"
	},
	{
		"id": "tt2582802",
		"title": "Whiplash",
		"year": 2014,
		"type": "Movie",
		"rating": 8,
		"runtime": 106,
		"genres": [
			"Drama",
			"Music"
		],
		"directors": [
			"Damien Chazelle"
		],
		"posterPath": "/7fn624j5lj3xTme2SgiLCeuedmO.jpg",
		"watched": 1,
		"watchedOn": "2025-06-19"
	},
	{
		"id": "tt2861424",
		"title": "Rick and Morty",
		"year": 2013,
		"type": "TV Series",
		"rating": 8,
		"runtime": 23,
		"genres": [
			"Animation",
			"Adventure",
			"Comedy",
			"Sci-Fi"
		],
		"directors": [],
		"posterPath": "/owhkU6KRqdXoUQpjV8uyZGPtX58.jpg",
		"watched": 1,
		"watchedOn": "2025-06-19"
	},
	{
		"id": "tt2576852",
		"title": "The Tale of The Princess Kaguya",
		"year": 2013,
		"type": "Movie",
		"rating": 8,
		"runtime": 137,
		"genres": [
			"Animation",
			"Drama",
			"Fantasy",
			"Family",
			"Romance"
		],
		"directors": [
			"Isao Takahata"
		],
		"posterPath": "/cQidJuA546OSSXKWXoiCeINDxuj.jpg",
		"watched": 1,
		"watchedOn": "2025-06-19"
	},
	{
		"id": "tt1345836",
		"title": "The Dark Knight Rises",
		"year": 2012,
		"type": "Movie",
		"rating": 8,
		"runtime": 164,
		"genres": [
			"Thriller",
			"Crime"
		],
		"directors": [
			"Christopher Nolan"
		],
		"posterPath": "/hr0L2aueqlP2BYUblTTjmtn0hw4.jpg",
		"watched": 1,
		"watchedOn": "2025-06-21"
	},
	{
		"id": "tt1645170",
		"title": "The Dictator",
		"year": 2012,
		"type": "Movie",
		"rating": 8,
		"runtime": 83,
		"genres": [
			"Comedy"
		],
		"directors": [
			"Larry Charles"
		],
		"posterPath": "/n0W7kajF4GFMRk2c0wWwMQqTaDM.jpg",
		"watched": 1,
		"watchedOn": "2026-03-23"
	},
	{
		"id": "tt0944947",
		"title": "Game of Thrones",
		"year": 2011,
		"type": "TV Series",
		"rating": 8,
		"runtime": 60,
		"genres": [
			"Fantasy",
			"Drama"
		],
		"directors": [],
		"posterPath": "/1XS1oqL89opfnbLl8WnZY1O1uJx.jpg",
		"watched": 1,
		"watchedOn": "2025-06-19"
	},
	{
		"id": "tt1298650",
		"title": "Pirates of the Caribbean: On Stranger Tides",
		"year": 2011,
		"type": "Movie",
		"rating": 8,
		"runtime": 136,
		"genres": [
			"Action",
			"Adventure",
			"Fantasy"
		],
		"directors": [
			"Rob Marshall"
		],
		"posterPath": "/keGfSvCmYj7CvdRx36OdVrAEibE.jpg",
		"watched": 1,
		"watchedOn": "2025-06-19"
	},
	{
		"id": "tt1568346",
		"title": "The Girl with the Dragon Tattoo",
		"year": 2011,
		"type": "Movie",
		"rating": 8,
		"runtime": 158,
		"genres": [
			"Drama",
			"Thriller",
			"Crime",
			"Mystery"
		],
		"directors": [
			"David Fincher"
		],
		"posterPath": "/8bokS83zGdhaXgN9tjidUKmAftW.jpg",
		"watched": 1,
		"watchedOn": "2023-05-16"
	},
	{
		"id": "tt1375666",
		"title": "Inception",
		"year": 2010,
		"type": "Movie",
		"rating": 8,
		"runtime": 148,
		"genres": [
			"Sci-Fi",
			"Thriller",
			"Adventure"
		],
		"directors": [
			"Christopher Nolan"
		],
		"posterPath": "/xlaY2zyzMfkhk0HSC5VUwzoZPU1.jpg",
		"watched": 1,
		"watchedOn": "2025-06-19"
	},
	{
		"id": "tt1130884",
		"title": "Shutter Island",
		"year": 2010,
		"type": "Movie",
		"rating": 8,
		"runtime": 138,
		"genres": [
			"Thriller",
			"Mystery",
			"Drama"
		],
		"directors": [
			"Martin Scorsese"
		],
		"posterPath": "/nrmXQ0zcZUL8jFLrakWc90IR8z9.jpg",
		"watched": 1,
		"watchedOn": "2025-03-11"
	},
	{
		"id": "tt1028532",
		"title": "Hachi: A Dog's Tale",
		"year": 2009,
		"type": "Movie",
		"rating": 8,
		"runtime": 93,
		"genres": [
			"Drama",
			"Family",
			"Biography"
		],
		"directors": [
			"Lasse Hallström"
		],
		"posterPath": "/lsy3aEsEfYIHdLRk4dontZ4s85h.jpg",
		"watched": 1,
		"watchedOn": "2026-05-21"
	},
	{
		"id": "tt1178180",
		"title": "The Marvelous Misadventures of Flapjack",
		"year": 2008,
		"type": "TV Series",
		"rating": 8,
		"runtime": 11,
		"genres": [
			"Animation",
			"Short",
			"Family",
			"Comedy",
			"Fantasy",
			"Adventure",
			"Horror"
		],
		"directors": [],
		"posterPath": "/8dpk0bjBgX93ZkQxEI1daNSj3OW.jpg",
		"watched": 1,
		"watchedOn": "2021-04-15"
	},
	{
		"id": "tt1125849",
		"title": "The Wrestler",
		"year": 2008,
		"type": "Movie",
		"rating": 8,
		"runtime": 109,
		"genres": [
			"Drama",
			"Sport"
		],
		"directors": [
			"Darren Aronofsky"
		],
		"posterPath": "/6OTR8dSoNGjWohJNo3UhIGd3Tj.jpg",
		"watched": 1,
		"watchedOn": "2021-04-06"
	},
	{
		"id": "tt0449088",
		"title": "Pirates of the Caribbean: At World's End",
		"year": 2007,
		"type": "Movie",
		"rating": 8,
		"runtime": 169,
		"genres": [
			"Action",
			"Adventure",
			"Fantasy"
		],
		"directors": [
			"Gore Verbinski"
		],
		"posterPath": "/jGWpG4YhpQwVmjyHEGkxEkeRf0S.jpg",
		"watched": 1,
		"watchedOn": "2025-06-19"
	},
	{
		"id": "tt0450259",
		"title": "Blood Diamond",
		"year": 2006,
		"type": "Movie",
		"rating": 8,
		"runtime": 143,
		"genres": [
			"Drama",
			"Adventure",
			"Thriller"
		],
		"directors": [
			"Edward Zwick"
		],
		"posterPath": "/tnLxPpajkbVdbQl5B9CuD7sSpz9.jpg",
		"watched": 1,
		"watchedOn": "2022-07-07"
	},
	{
		"id": "tt0877057",
		"title": "Death Note",
		"year": 2006,
		"type": "TV Series",
		"rating": 8,
		"runtime": 24,
		"genres": [
			"Animation",
			"Mystery",
			"Crime",
			"Thriller",
			"Fantasy",
			"Drama"
		],
		"directors": [],
		"posterPath": "/tCZFfYTIwrR7n94J6G14Y4hAFU6.jpg",
		"watched": 1,
		"watchedOn": "2021-03-09"
	},
	{
		"id": "tt0383574",
		"title": "Pirates of the Caribbean: Dead Man's Chest",
		"year": 2006,
		"type": "Movie",
		"rating": 8,
		"runtime": 151,
		"genres": [
			"Adventure",
			"Fantasy",
			"Action"
		],
		"directors": [
			"Gore Verbinski"
		],
		"posterPath": "/uXEqmloGyP7UXAiphJUu2v2pcuE.jpg",
		"watched": 1,
		"watchedOn": "2025-06-19"
	},
	{
		"id": "tt0482571",
		"title": "The Prestige",
		"year": 2006,
		"type": "Movie",
		"rating": 8,
		"runtime": 130,
		"genres": [
			"Drama",
			"Thriller",
			"Mystery",
			"Sci-Fi"
		],
		"directors": [
			"Christopher Nolan"
		],
		"posterPath": "/Ag2B2KHKQPukjH7WutmgnnSNurZ.jpg",
		"watched": 1,
		"watchedOn": "2024-08-03"
	},
	{
		"id": "tt0455275",
		"title": "Prison Break",
		"year": 2005,
		"type": "TV Series",
		"rating": 8,
		"runtime": 44,
		"genres": [
			"Mystery",
			"Thriller",
			"Crime",
			"Drama",
			"Action"
		],
		"directors": [],
		"posterPath": "/wnmNPaLvhnMeOqnWlhNkYCZxtda.jpg",
		"watched": 1,
		"watchedOn": "2021-01-27"
	},
	{
		"id": "tt0434409",
		"title": "V for Vendetta",
		"year": 2005,
		"type": "Movie",
		"rating": 8,
		"runtime": 132,
		"genres": [
			"Thriller",
			"Action",
			"Drama",
			"Sci-Fi"
		],
		"directors": [
			"James McTeigue"
		],
		"posterPath": "/1avD1JeaRiJX5M4ahPdZPypGoGN.jpg",
		"watched": 1,
		"watchedOn": "2020-12-03"
	},
	{
		"id": "tt0338013",
		"title": "Eternal Sunshine of the Spotless Mind",
		"year": 2004,
		"type": "Movie",
		"rating": 8,
		"runtime": 108,
		"genres": [
			"Drama",
			"Sci-Fi",
			"Romance"
		],
		"directors": [
			"Michel Gondry"
		],
		"posterPath": "/5MwkWH9tYHv3mV9OdYTMR5qreIz.jpg",
		"watched": 1,
		"watchedOn": "2023-04-23"
	},
	{
		"id": "tt0347149",
		"title": "Howl's Moving Castle",
		"year": 2004,
		"type": "Movie",
		"rating": 8,
		"runtime": 119,
		"genres": [
			"Animation",
			"Adventure",
			"Family",
			"Fantasy"
		],
		"directors": [
			"Hayao Miyazaki"
		],
		"posterPath": "/13kOl2v0nD2OLbVSHnHk8GUFEhO.jpg",
		"watched": 1,
		"watchedOn": "2021-09-13"
	},
	{
		"id": "tt0327056",
		"title": "Mystic River",
		"year": 2003,
		"type": "Movie",
		"rating": 8,
		"runtime": 138,
		"genres": [
			"Crime",
			"Mystery",
			"Thriller",
			"Drama"
		],
		"directors": [
			"Clint Eastwood"
		],
		"posterPath": "/hCHVDbo6XJGj3r2i4hVjKhE0GKF.jpg",
		"watched": 1,
		"watchedOn": "2021-08-29"
	},
	{
		"id": "tt0325980",
		"title": "Pirates of the Caribbean: The Curse of the Black Pearl",
		"year": 2003,
		"type": "Movie",
		"rating": 8,
		"runtime": 143,
		"genres": [
			"Fantasy",
			"Action",
			"Adventure"
		],
		"directors": [
			"Gore Verbinski"
		],
		"posterPath": "/poHwCZeWzJCShH7tOjg8RIoyjcw.jpg",
		"watched": 1,
		"watchedOn": "2025-06-19"
	},
	{
		"id": "tt0253474",
		"title": "The Pianist",
		"year": 2002,
		"type": "Movie",
		"rating": 8,
		"runtime": 150,
		"genres": [
			"Biography",
			"Music",
			"Drama",
			"War"
		],
		"directors": [
			"Roman Polanski"
		],
		"posterPath": "/2hFvxCCWrTmCYwfy7yum0GKRi3Y.jpg",
		"watched": 1,
		"watchedOn": "2022-07-23"
	},
	{
		"id": "tt0144084",
		"title": "American Psycho",
		"year": 2000,
		"type": "Movie",
		"rating": 8,
		"runtime": 102,
		"genres": [
			"Crime",
			"Horror",
			"Drama"
		],
		"directors": [
			"Mary Harron"
		],
		"posterPath": "/9uGHEgsiUXjCNq8wdq4r49YL8A1.jpg",
		"watched": 1,
		"watchedOn": "2023-05-16"
	},
	{
		"id": "tt0172495",
		"title": "Gladiator",
		"year": 2000,
		"type": "Movie",
		"rating": 8,
		"runtime": 155,
		"genres": [
			"Action",
			"Adventure",
			"Drama"
		],
		"directors": [
			"Ridley Scott"
		],
		"posterPath": "/wN2xWp1eIwCKOD0BHTcErTBv1Uq.jpg",
		"watched": 1,
		"watchedOn": "2021-06-22"
	},
	{
		"id": "tt0209144",
		"title": "Memento",
		"year": 2000,
		"type": "Movie",
		"rating": 8,
		"runtime": 113,
		"genres": [
			"Thriller",
			"Mystery"
		],
		"directors": [
			"Christopher Nolan"
		],
		"posterPath": "/fKTPH2WvH8nHTXeBYBVhawtRqtR.jpg",
		"watched": 1,
		"watchedOn": "2023-07-10"
	},
	{
		"id": "tt0169547",
		"title": "American Beauty",
		"year": 1999,
		"type": "Movie",
		"rating": 8,
		"runtime": 122,
		"genres": [
			"Drama"
		],
		"directors": [
			"Sam Mendes"
		],
		"posterPath": "/wby9315QzVKdW9BonAefg8jGTTb.jpg",
		"watched": 1,
		"watchedOn": "2023-04-23"
	},
	{
		"id": "tt0137523",
		"title": "Fight Club",
		"year": 1999,
		"type": "Movie",
		"rating": 8,
		"runtime": 139,
		"genres": [
			"Drama",
			"Crime",
			"Thriller"
		],
		"directors": [
			"David Fincher"
		],
		"posterPath": "/jSziioSwPVrOy9Yow3XhWIBDjq1.jpg",
		"watched": 1,
		"watchedOn": "2023-04-23"
	},
	{
		"id": "tt0133093",
		"title": "The Matrix",
		"year": 1999,
		"type": "Movie",
		"rating": 8,
		"runtime": 136,
		"genres": [
			"Action",
			"Sci-Fi"
		],
		"directors": [
			"Lana Wachowski",
			"Lilly Wachowski"
		],
		"posterPath": "/dXNAPwY7VrqMAo51EKhhCJfaGb5.jpg",
		"watched": 1,
		"watchedOn": "2025-06-19"
	},
	{
		"id": "tt0120382",
		"title": "The Truman Show",
		"year": 1998,
		"type": "Movie",
		"rating": 8,
		"runtime": 103,
		"genres": [
			"Comedy",
			"Drama"
		],
		"directors": [
			"Peter Weir"
		],
		"posterPath": "/vuza0WqY239yBXOadKlGwJsZJFE.jpg",
		"watched": 1,
		"watchedOn": "2021-05-22"
	},
	{
		"id": "tt0113824",
		"title": "Whisper of the Heart",
		"year": 1995,
		"type": "Movie",
		"rating": 8,
		"runtime": 111,
		"genres": [
			"Animation",
			"Family",
			"Romance",
			"Drama"
		],
		"directors": [
			"Yoshifumi Kondō"
		],
		"posterPath": "/5FROLD8zpWFs9ja7aYho1uOMJHg.jpg",
		"watched": 1,
		"watchedOn": "2025-06-19"
	},
	{
		"id": "tt0109830",
		"title": "Forrest Gump",
		"year": 1994,
		"type": "Movie",
		"rating": 8,
		"runtime": 142,
		"genres": [
			"Romance",
			"Drama"
		],
		"directors": [
			"Robert Zemeckis"
		],
		"posterPath": "/Cw4hIUIAmSYfK9QfaUW5igp9La.jpg",
		"watched": 1,
		"watchedOn": "2022-01-19"
	},
	{
		"id": "tt0111161",
		"title": "The Shawshank Redemption",
		"year": 1994,
		"type": "Movie",
		"rating": 8,
		"runtime": 142,
		"genres": [
			"Drama"
		],
		"directors": [
			"Frank Darabont"
		],
		"posterPath": "/9cqNxx0GxF0bflZmeSMuL5tnGzr.jpg",
		"watched": 1,
		"watchedOn": "2025-06-19"
	},
	{
		"id": "tt0105323",
		"title": "Scent of a Woman",
		"year": 1992,
		"type": "Movie",
		"rating": 8,
		"runtime": 156,
		"genres": [
			"Drama"
		],
		"directors": [
			"Martin Brest"
		],
		"posterPath": "/4adI7IaveWb7EidYXfLb3MK3CgO.jpg",
		"watched": 1,
		"watchedOn": "2025-06-19"
	},
	{
		"id": "tt0096283",
		"title": "My Neighbor Totoro",
		"year": 1988,
		"type": "Movie",
		"rating": 8,
		"runtime": 86,
		"genres": [
			"Animation",
			"Family",
			"Comedy",
			"Adventure",
			"Fantasy"
		],
		"directors": [
			"Hayao Miyazaki"
		],
		"posterPath": "/rtGDOeG9LzoerkDGZF9dnVeLppL.jpg",
		"watched": 1,
		"watchedOn": "2021-09-14"
	},
	{
		"id": "tt0093058",
		"title": "Full Metal Jacket",
		"year": 1987,
		"type": "Movie",
		"rating": 8,
		"runtime": 116,
		"genres": [
			"Drama",
			"War"
		],
		"directors": [
			"Stanley Kubrick"
		],
		"posterPath": "/kMKyx1k8hWWscYFnPbnxxN4Eqo4.jpg",
		"watched": 1,
		"watchedOn": "2025-06-19"
	},
	{
		"id": "tt0092067",
		"title": "Castle in the Sky",
		"year": 1986,
		"type": "Movie",
		"rating": 8,
		"runtime": 124,
		"genres": [
			"Animation",
			"Fantasy",
			"Family",
			"Adventure"
		],
		"directors": [
			"Hayao Miyazaki"
		],
		"posterPath": "/41XxSsJc5OrulP0m7TrrUeO2hoz.jpg",
		"watched": 1,
		"watchedOn": "2021-09-05"
	},
	{
		"id": "tt12300742",
		"title": "Bugonia",
		"year": 2025,
		"type": "Movie",
		"rating": 7,
		"runtime": 118,
		"genres": [
			"Sci-Fi",
			"Comedy",
			"Crime",
			"Thriller"
		],
		"directors": [
			"Yorgos Lanthimos"
		],
		"posterPath": "/oxgsAQDAAxA92mFGYCZllgWkH9J.jpg",
		"watched": 1,
		"watchedOn": "2026-03-23"
	},
	{
		"id": "tt30144839",
		"title": "One Battle After Another",
		"year": 2025,
		"type": "Movie",
		"rating": 7,
		"runtime": 161,
		"genres": [
			"Crime",
			"Drama",
			"Thriller"
		],
		"directors": [
			"Paul Thomas Anderson"
		],
		"posterPath": "/lbBWwxBht4JFP5PsuJ5onpMqugW.jpg",
		"watched": 1,
		"watchedOn": "2026-03-23"
	},
	{
		"id": "tt6741278",
		"title": "Invincible",
		"year": 2021,
		"type": "TV Series",
		"rating": 7,
		"runtime": 50,
		"genres": [
			"Animation",
			"Sci-Fi",
			"Action",
			"Drama",
			"Adventure",
			"Fantasy",
			"Thriller"
		],
		"directors": [],
		"posterPath": "/4tblBrslcKSifMVZ3TmtT2ukMor.jpg",
		"watched": 1,
		"watchedOn": "2022-07-07"
	},
	{
		"id": "tt2382320",
		"title": "No Time to Die",
		"year": 2021,
		"type": "Movie",
		"rating": 7,
		"runtime": 163,
		"genres": [
			"Action",
			"Thriller",
			"Adventure"
		],
		"directors": [
			"Cary Joji Fukunaga"
		],
		"posterPath": "/iUgygt3fscRoKWCV1d0C7FbM9TP.jpg",
		"watched": 1,
		"watchedOn": "2021-10-11"
	},
	{
		"id": "tt10919420",
		"title": "Squid Game",
		"year": 2021,
		"type": "TV Series",
		"rating": 7,
		"runtime": 60,
		"genres": [
			"Mystery",
			"Thriller",
			"Drama",
			"Action",
			"Crime"
		],
		"directors": [],
		"posterPath": "/1QdXdRYfktUSONkl1oD5gc6Be0s.jpg",
		"watched": 1,
		"watchedOn": "2021-10-08"
	},
	{
		"id": "tt7737786",
		"title": "Greenland",
		"year": 2020,
		"type": "Movie",
		"rating": 7,
		"runtime": 119,
		"genres": [
			"Thriller",
			"Action",
			"Adventure"
		],
		"directors": [
			"Ric Roman Waugh"
		],
		"posterPath": "/bNo2mcvSwIvnx8K6y1euAc1TLVq.jpg",
		"watched": 1,
		"watchedOn": "2021-03-09"
	},
	{
		"id": "tt11768948",
		"title": "If Anything Happens I Love You",
		"year": 2020,
		"type": "Short",
		"rating": 7,
		"runtime": 13,
		"genres": [
			"Animation",
			"Short",
			"Drama"
		],
		"directors": [
			"Michael Govier",
			"Will McCormack"
		],
		"posterPath": "/85tDhACvKDQxQoJhBYLvDU0ik1n.jpg",
		"watched": 1,
		"watchedOn": "2021-05-19"
	},
	{
		"id": "tt9686708",
		"title": "The King of Staten Island",
		"year": 2020,
		"type": "Movie",
		"rating": 7,
		"runtime": 136,
		"genres": [
			"Comedy",
			"Drama"
		],
		"directors": [
			"Judd Apatow"
		],
		"posterPath": "/zQFjMmE3K9AX5QrBL1SXIxYQ9jz.jpg",
		"watched": 1,
		"watchedOn": "2021-04-06"
	},
	{
		"id": "tt9561862",
		"title": "Love, Death & Robots",
		"year": 2019,
		"type": "TV Series",
		"rating": 7,
		"runtime": 15,
		"genres": [
			"Animation",
			"Short",
			"Comedy",
			"Fantasy",
			"Horror",
			"Sci-Fi",
			"Action",
			"Adventure",
			"Drama",
			"Mystery",
			"Thriller"
		],
		"directors": [],
		"posterPath": "/vL5BQvXH96cJzmNK5n7QliQxy90.jpg",
		"watched": 1,
		"watchedOn": "2021-05-22"
	},
	{
		"id": "tt1190634",
		"title": "The Boys",
		"year": 2019,
		"type": "TV Series",
		"rating": 7,
		"runtime": 60,
		"genres": [
			"Action",
			"Sci-Fi",
			"Crime",
			"Comedy",
			"Drama"
		],
		"directors": [],
		"posterPath": "/in1R2dDc421JxsoRWaIIAqVI2KE.jpg",
		"watched": 1,
		"watchedOn": "2022-07-07"
	},
	{
		"id": "tt4154756",
		"title": "Avengers: Infinity War",
		"year": 2018,
		"type": "Movie",
		"rating": 7,
		"runtime": 149,
		"genres": [
			"Action",
			"Sci-Fi",
			"Adventure"
		],
		"directors": [
			"Anthony Russo",
			"Joe Russo"
		],
		"posterPath": "/7WsyChQLEftFiDOVTGkv3hFpyyt.jpg",
		"watched": 1,
		"watchedOn": "2020-12-03"
	},
	{
		"id": "tt5348176",
		"title": "Barry",
		"year": 2018,
		"type": "TV Series",
		"rating": 7,
		"runtime": 30,
		"genres": [
			"Comedy",
			"Crime",
			"Drama",
			"Action"
		],
		"directors": [],
		"posterPath": "/j1XpwD11f0BAEI7pX6UdMhUVX2F.jpg",
		"watched": 1,
		"watchedOn": "2021-06-23"
	},
	{
		"id": "tt5463162",
		"title": "Deadpool 2",
		"year": 2018,
		"type": "Movie",
		"rating": 7,
		"runtime": 119,
		"genres": [
			"Action",
			"Adventure",
			"Comedy",
			"Sci-Fi"
		],
		"directors": [
			"David Leitch"
		],
		"posterPath": "/to0spRl1CMDvyUbOnbb4fTk3VAd.jpg",
		"watched": 1,
		"watchedOn": "2021-01-27"
	},
	{
		"id": "tt6966692",
		"title": "Green Book",
		"year": 2018,
		"type": "Movie",
		"rating": 7,
		"runtime": 130,
		"genres": [
			"Drama",
			"Biography",
			"Comedy",
			"Music"
		],
		"directors": [
			"Peter Farrelly"
		],
		"posterPath": "/7BsvSuDQuoqhWmU2fL7W2GOcZHU.jpg",
		"watched": 1,
		"watchedOn": "2023-05-16"
	},
	{
		"id": "tt6908274",
		"title": "Mirage",
		"year": 2018,
		"type": "Movie",
		"rating": 7,
		"runtime": 128,
		"genres": [
			"Drama",
			"Thriller",
			"Romance",
			"Mystery",
			"Fantasy"
		],
		"directors": [
			"Oriol Paulo"
		],
		"posterPath": "/hmhYM1CNBhpWTYjUEZ4leQDmIYw.jpg",
		"watched": 1,
		"watchedOn": "2020-12-03"
	},
	{
		"id": "tt7335184",
		"title": "You",
		"year": 2018,
		"type": "TV Series",
		"rating": 7,
		"runtime": 45,
		"genres": [
			"Drama",
			"Crime",
			"Thriller",
			"Romance"
		],
		"directors": [],
		"posterPath": "/oANi0vEE92nuijiZQgPZ88FSxqQ.jpg",
		"watched": 1,
		"watchedOn": "2021-04-06"
	},
	{
		"id": "tt5052448",
		"title": "Get Out",
		"year": 2017,
		"type": "Movie",
		"rating": 7,
		"runtime": 104,
		"genres": [
			"Horror",
			"Mystery",
			"Thriller"
		],
		"directors": [
			"Jordan Peele"
		],
		"posterPath": "/mE24wUCfjK8AoBBjaMjho7Rczr7.jpg",
		"watched": 1,
		"watchedOn": "2020-12-03"
	},
	{
		"id": "tt6470478",
		"title": "The Good Doctor",
		"year": 2017,
		"type": "TV Series",
		"rating": 7,
		"runtime": 45,
		"genres": [
			"Drama"
		],
		"directors": [],
		"posterPath": "/luhKkdD80qe62fwop6sdrXK9jUT.jpg",
		"watched": 1,
		"watchedOn": "2021-06-22"
	},
	{
		"id": "tt3501632",
		"title": "Thor: Ragnarok",
		"year": 2017,
		"type": "Movie",
		"rating": 7,
		"runtime": 130,
		"genres": [
			"Action",
			"Sci-Fi",
			"Adventure",
			"Comedy",
			"Fantasy"
		],
		"directors": [
			"Taika Waititi"
		],
		"posterPath": "/rzRwTcFvttcN1ZpX2xv4j3tSdJu.jpg",
		"watched": 1,
		"watchedOn": "2020-12-03"
	},
	{
		"id": "tt1431045",
		"title": "Deadpool",
		"year": 2016,
		"type": "Movie",
		"rating": 7,
		"runtime": 108,
		"genres": [
			"Action",
			"Sci-Fi",
			"Comedy"
		],
		"directors": [
			"Tim Miller"
		],
		"posterPath": "/3E53WEZJqP6aM84D8CckXx4pIHw.jpg",
		"watched": 1,
		"watchedOn": "2020-12-03"
	},
	{
		"id": "tt1211837",
		"title": "Doctor Strange",
		"year": 2016,
		"type": "Movie",
		"rating": 7,
		"runtime": 115,
		"genres": [
			"Fantasy",
			"Adventure",
			"Action",
			"Sci-Fi"
		],
		"directors": [
			"Scott Derrickson"
		],
		"posterPath": "/xf8PbyQcR5ucXErmZNzdKR0s8ya.jpg",
		"watched": 1,
		"watchedOn": "2020-12-03"
	},
	{
		"id": "tt3110958",
		"title": "Now You See Me 2",
		"year": 2016,
		"type": "Movie",
		"rating": 7,
		"runtime": 129,
		"genres": [
			"Comedy",
			"Thriller",
			"Action",
			"Adventure",
			"Mystery",
			"Crime"
		],
		"directors": [
			"Jon M. Chu"
		],
		"posterPath": "/A81kDB6a1K86YLlcOtZB27jriJh.jpg",
		"watched": 1,
		"watchedOn": "2021-01-18"
	},
	{
		"id": "tt4574334",
		"title": "Stranger Things",
		"year": 2016,
		"type": "TV Series",
		"rating": 7,
		"runtime": 60,
		"genres": [
			"Drama",
			"Horror",
			"Thriller",
			"Sci-Fi",
			"Mystery",
			"Fantasy"
		],
		"directors": [],
		"posterPath": "/uOOtwVbSr4QDjAGIifLDwpb2Pdl.jpg",
		"watched": 1,
		"watchedOn": "2020-12-03"
	},
	{
		"id": "tt2140479",
		"title": "The Accountant",
		"year": 2016,
		"type": "Movie",
		"rating": 7,
		"runtime": 128,
		"genres": [
			"Thriller",
			"Action",
			"Crime",
			"Drama"
		],
		"directors": [
			"Gavin O'Connor"
		],
		"posterPath": "/fceheXB5fC4WrLVuWJ6OZv9FXYr.jpg",
		"watched": 1,
		"watchedOn": "2022-02-12"
	},
	{
		"id": "tt4857264",
		"title": "The Invisible Guest",
		"year": 2016,
		"type": "Movie",
		"rating": 7,
		"runtime": 106,
		"genres": [
			"Thriller",
			"Crime",
			"Mystery",
			"Drama"
		],
		"directors": [
			"Oriol Paulo"
		],
		"posterPath": "/fptnZJbLzKUHeNlYrAynbyoL5YJ.jpg",
		"watched": 1,
		"watchedOn": "2021-05-25"
	},
	{
		"id": "tt2361509",
		"title": "The Intern",
		"year": 2015,
		"type": "Movie",
		"rating": 7,
		"runtime": 121,
		"genres": [
			"Comedy",
			"Drama"
		],
		"directors": [
			"Nancy Meyers"
		],
		"posterPath": "/bTQ46fupPbjBfFBHuzfD3hxxL0Q.jpg",
		"watched": 1,
		"watchedOn": "2025-06-10"
	},
	{
		"id": "tt1663202",
		"title": "The Revenant",
		"year": 2015,
		"type": "Movie",
		"rating": 7,
		"runtime": 156,
		"genres": [
			"Action",
			"Drama",
			"Western"
		],
		"directors": [
			"Alejandro G. Iñárritu"
		],
		"posterPath": "/ji3ecJphATlVgWNY0B0RVXZizdf.jpg",
		"watched": 1,
		"watchedOn": "2023-05-16"
	},
	{
		"id": "tt2870612",
		"title": "As Above, So Below",
		"year": 2014,
		"type": "Movie",
		"rating": 7,
		"runtime": 93,
		"genres": [
			"Thriller",
			"Horror",
			"Mystery",
			"Adventure"
		],
		"directors": [
			"John Erick Dowdle"
		],
		"posterPath": "/oJZSajKLJkoTOzSZQN2ZwRnPwHZ.jpg",
		"watched": 1,
		"watchedOn": "2026-03-23"
	},
	{
		"id": "tt2267998",
		"title": "Gone Girl",
		"year": 2014,
		"type": "Movie",
		"rating": 7,
		"runtime": 149,
		"genres": [
			"Thriller",
			"Drama",
			"Mystery"
		],
		"directors": [
			"David Fincher"
		],
		"posterPath": "/ts996lKsxvjkO2yiYG0ht4qAicO.jpg",
		"watched": 1,
		"watchedOn": "2023-05-13"
	},
	{
		"id": "tt2015381",
		"title": "Guardians of the Galaxy",
		"year": 2014,
		"type": "Movie",
		"rating": 7,
		"runtime": 121,
		"genres": [
			"Sci-Fi",
			"Action",
			"Adventure",
			"Comedy"
		],
		"directors": [
			"James Gunn"
		],
		"posterPath": "/r7vmZjiyZw9rpJMQJdXpjgiCOk9.jpg",
		"watched": 1,
		"watchedOn": "2020-12-03"
	},
	{
		"id": "tt2560140",
		"title": "Attack on Titan",
		"year": 2013,
		"type": "TV Series",
		"rating": 7,
		"runtime": 24,
		"genres": [
			"Animation",
			"Fantasy",
			"Horror",
			"Adventure",
			"Drama",
			"Action"
		],
		"directors": [],
		"posterPath": "/hTP1DtLGFamjfu8WqjnuQdP1n4i.jpg",
		"watched": 1,
		"watchedOn": "2021-05-18"
	},
	{
		"id": "tt1798709",
		"title": "Her",
		"year": 2013,
		"type": "Movie",
		"rating": 7,
		"runtime": 126,
		"genres": [
			"Romance",
			"Sci-Fi",
			"Drama"
		],
		"directors": [
			"Spike Jonze"
		],
		"posterPath": "/eCOtqtfvn7mxGl6nfmq4b1exJRc.jpg",
		"watched": 1,
		"watchedOn": "2023-05-16"
	},
	{
		"id": "tt1670345",
		"title": "Now You See Me",
		"year": 2013,
		"type": "Movie",
		"rating": 7,
		"runtime": 115,
		"genres": [
			"Thriller",
			"Crime",
			"Mystery"
		],
		"directors": [
			"Louis Leterrier"
		],
		"posterPath": "/tWsNYbrqy1p1w6K9zRk0mSchztT.jpg",
		"watched": 1,
		"watchedOn": "2021-01-10"
	},
	{
		"id": "tt1392214",
		"title": "Prisoners",
		"year": 2013,
		"type": "Movie",
		"rating": 7,
		"runtime": 153,
		"genres": [
			"Crime",
			"Drama",
			"Thriller",
			"Mystery"
		],
		"directors": [
			"Denis Villeneuve"
		],
		"posterPath": "/jsS3a3ep2KyBVmmiwaz3LvK49b1.jpg",
		"watched": 1,
		"watchedOn": "2023-05-16"
	},
	{
		"id": "tt1706620",
		"title": "Snowpiercer",
		"year": 2013,
		"type": "Movie",
		"rating": 7,
		"runtime": 126,
		"genres": [
			"Sci-Fi",
			"Thriller",
			"Action",
			"Drama"
		],
		"directors": [
			"Bong Joon Ho"
		],
		"posterPath": "/kw6YQudA0TMcNmGUGy5XIw7zbnV.jpg",
		"watched": 1,
		"watchedOn": "2023-07-10"
	},
	{
		"id": "tt1790885",
		"title": "Zero Dark Thirty",
		"year": 2012,
		"type": "Movie",
		"rating": 7,
		"runtime": 157,
		"genres": [
			"Thriller",
			"Drama",
			"History"
		],
		"directors": [
			"Kathryn Bigelow"
		],
		"posterPath": "/wNSdSSxowM3WIqmPJNg3RagYbwP.jpg",
		"watched": 1,
		"watchedOn": "2025-01-27"
	},
	{
		"id": "tt2085059",
		"title": "Black Mirror",
		"year": 2011,
		"type": "TV Series",
		"rating": 7,
		"runtime": 60,
		"genres": [
			"Drama",
			"Thriller",
			"Sci-Fi",
			"Mystery",
			"Crime"
		],
		"directors": [],
		"posterPath": "/seN6rRfN0I6n8iDXjlSMk1QjNcq.jpg",
		"watched": 1,
		"watchedOn": "2021-01-27"
	},
	{
		"id": "tt1723811",
		"title": "Shame",
		"year": 2011,
		"type": "Movie",
		"rating": 7,
		"runtime": 101,
		"genres": [
			"Drama"
		],
		"directors": [
			"Steve McQueen"
		],
		"posterPath": "/cAWLz9kFv4xc6IsEXTj2DrcqD55.jpg",
		"watched": 1,
		"watchedOn": "2025-06-20"
	},
	{
		"id": "tt1675192",
		"title": "Take Shelter",
		"year": 2011,
		"type": "Movie",
		"rating": 7,
		"runtime": 120,
		"genres": [
			"Drama",
			"Thriller"
		],
		"directors": [
			"Jeff Nichols"
		],
		"posterPath": "/dldIX0q5jewe8rSyCh8d5I1RYx3.jpg",
		"watched": 1,
		"watchedOn": "2022-04-21"
	},
	{
		"id": "tt1510938",
		"title": "The Sunset Limited",
		"year": 2011,
		"type": "TV Movie",
		"rating": 7,
		"runtime": 91,
		"genres": [
			"Drama"
		],
		"directors": [
			"Tommy Lee Jones"
		],
		"posterPath": "/8cwqylJVbCfMflcjXQ71CwsXdpf.jpg",
		"watched": 1,
		"watchedOn": "2020-12-03"
	},
	{
		"id": "tt0443543",
		"title": "The Illusionist",
		"year": 2006,
		"type": "Movie",
		"rating": 7,
		"runtime": 110,
		"genres": [
			"Drama",
			"Romance",
			"Mystery",
			"Thriller",
			"Fantasy"
		],
		"directors": [
			"Neil Burger"
		],
		"posterPath": "/1O9jUvqkHaGBMVRyOJz1AlkmALW.jpg",
		"watched": 1,
		"watchedOn": "2021-01-19"
	},
	{
		"id": "tt0372784",
		"title": "Batman Begins",
		"year": 2005,
		"type": "Movie",
		"rating": 7,
		"runtime": 140,
		"genres": [
			"Crime"
		],
		"directors": [
			"Christopher Nolan"
		],
		"posterPath": "/sPX89Td70IDDjVr85jdSBb4rWGr.jpg",
		"watched": 1,
		"watchedOn": "2020-12-03"
	},
	{
		"id": "tt0364569",
		"title": "Oldboy",
		"year": 2003,
		"type": "Movie",
		"rating": 7,
		"runtime": 120,
		"genres": [
			"Mystery",
			"Thriller",
			"Action",
			"Drama"
		],
		"directors": [
			"Park Chan-wook"
		],
		"posterPath": "/pWDtjs568ZfOTMbURQBYuT4Qxka.jpg",
		"watched": 1,
		"watchedOn": "2021-07-31"
	},
	{
		"id": "tt0409591",
		"title": "Naruto",
		"year": 2002,
		"type": "TV Series",
		"rating": 7,
		"runtime": 24,
		"genres": [
			"Animation",
			"Action",
			"Comedy",
			"Adventure",
			"Fantasy"
		],
		"directors": [],
		"posterPath": "/xppeysfvDKVx775MFuH8Z9BlpMk.jpg",
		"watched": 1,
		"watchedOn": "2021-01-27"
	},
	{
		"id": "tt0266915",
		"title": "Rush Hour 2",
		"year": 2001,
		"type": "Movie",
		"rating": 7,
		"runtime": 90,
		"genres": [
			"Thriller",
			"Crime",
			"Comedy",
			"Action"
		],
		"directors": [
			"Brett Ratner"
		],
		"posterPath": "/aBQf2vMiCINeVC9v6BGVYKXurTh.jpg",
		"watched": 1,
		"watchedOn": "2021-01-18"
	},
	{
		"id": "tt0120812",
		"title": "Rush Hour",
		"year": 1998,
		"type": "Movie",
		"rating": 7,
		"runtime": 98,
		"genres": [
			"Thriller",
			"Crime",
			"Comedy",
			"Action"
		],
		"directors": [
			"Brett Ratner"
		],
		"posterPath": "/we7wOLVFgxhzLzUt0qNe50xdIQZ.jpg",
		"watched": 1,
		"watchedOn": "2021-01-09"
	},
	{
		"id": "tt0109686",
		"title": "Dumb and Dumber",
		"year": 1994,
		"type": "Movie",
		"rating": 7,
		"runtime": 107,
		"genres": [
			"Comedy"
		],
		"directors": [
			"Peter Farrelly",
			"Bobby Farrelly"
		],
		"posterPath": "/4LdpBXiCyGKkR8FGHgjKlphrfUc.jpg",
		"watched": 1,
		"watchedOn": "2020-12-03"
	},
	{
		"id": "tt0110357",
		"title": "The Lion King",
		"year": 1994,
		"type": "Movie",
		"rating": 7,
		"runtime": 88,
		"genres": [
			"Animation",
			"Musical",
			"Drama",
			"Adventure",
			"Family"
		],
		"directors": [
			"Roger Allers",
			"Rob Minkoff"
		],
		"posterPath": "/sKCr78MXSLixwmZ8DyJLrpMsd15.jpg",
		"watched": 1,
		"watchedOn": "2020-12-03"
	},
	{
		"id": "tt6263850",
		"title": "Deadpool & Wolverine",
		"year": 2024,
		"type": "Movie",
		"rating": 6,
		"runtime": 128,
		"genres": [
			"Action",
			"Comedy",
			"Sci-Fi",
			"Adventure"
		],
		"directors": [
			"Shawn Levy"
		],
		"posterPath": "/8cdWjvZQUExUUTzyp4t6EDMubfO.jpg",
		"watched": 1,
		"watchedOn": "2024-08-03"
	},
	{
		"id": "tt9140554",
		"title": "Loki",
		"year": 2021,
		"type": "TV Series",
		"rating": 6,
		"runtime": 50,
		"genres": [
			"Fantasy",
			"Sci-Fi",
			"Action",
			"Adventure"
		],
		"directors": [],
		"posterPath": "/kEl2t3OhXc3Zb9FBh1AuYzRTgZp.jpg",
		"watched": 1,
		"watchedOn": "2021-06-23"
	},
	{
		"id": "tt7888964",
		"title": "Nobody",
		"year": 2021,
		"type": "Movie",
		"rating": 6,
		"runtime": 92,
		"genres": [
			"Action",
			"Crime",
			"Thriller",
			"Drama"
		],
		"directors": [
			"Ilya Naishuller"
		],
		"posterPath": "/oBgWY00bEFeZ9N25wWVyuQddbAo.jpg",
		"watched": 1,
		"watchedOn": "2021-05-19"
	},
	{
		"id": "tt9376612",
		"title": "Shang-Chi and the Legend of the Ten Rings",
		"year": 2021,
		"type": "Movie",
		"rating": 6,
		"runtime": 132,
		"genres": [
			"Action",
			"Adventure",
			"Fantasy",
			"Sci-Fi"
		],
		"directors": [
			"Destin Daniel Cretton"
		],
		"posterPath": "/9f2Q0U3IOsLgrI2HkvldwSABZy5.jpg",
		"watched": 1,
		"watchedOn": "2021-09-16"
	},
	{
		"id": "tt9421570",
		"title": "The Guilty",
		"year": 2021,
		"type": "Movie",
		"rating": 6,
		"runtime": 90,
		"genres": [
			"Drama",
			"Thriller",
			"Crime"
		],
		"directors": [
			"Antoine Fuqua"
		],
		"posterPath": "/m8aR1k35oZMOzZ1kYWUyt401mwq.jpg",
		"watched": 1,
		"watchedOn": "2022-02-12"
	},
	{
		"id": "tt1502397",
		"title": "Bad Boys for Life",
		"year": 2020,
		"type": "Movie",
		"rating": 6,
		"runtime": 124,
		"genres": [
			"Action",
			"Comedy",
			"Thriller",
			"Crime"
		],
		"directors": [
			"Adil El Arbi",
			"Bilall Fallah"
		],
		"posterPath": "/y95lQLnuNKdPAzw9F9Ab8kJ80c3.jpg",
		"watched": 1,
		"watchedOn": "2020-12-03"
	},
	{
		"id": "tt7846844",
		"title": "Enola Holmes",
		"year": 2020,
		"type": "Movie",
		"rating": 6,
		"runtime": 123,
		"genres": [
			"Drama",
			"Mystery",
			"Crime",
			"Adventure"
		],
		"directors": [
			"Harry Bradbeer"
		],
		"posterPath": "/riYInlsq2kf1AWoGm80JQW5dLKp.jpg",
		"watched": 1,
		"watchedOn": "2021-06-22"
	},
	{
		"id": "tt6723592",
		"title": "Tenet",
		"year": 2020,
		"type": "Movie",
		"rating": 6,
		"runtime": 150,
		"genres": [
			"Action",
			"Sci-Fi",
			"Thriller"
		],
		"directors": [
			"Christopher Nolan"
		],
		"posterPath": "/aCIFMriQh8rvhxpN1IWGgvH0Tlg.jpg",
		"watched": 1,
		"watchedOn": "2025-06-25"
	},
	{
		"id": "tt7440726",
		"title": "Your Honor",
		"year": 2020,
		"type": "TV Series",
		"rating": 6,
		"runtime": 60,
		"genres": [
			"Drama",
			"Crime",
			"Thriller"
		],
		"directors": [],
		"posterPath": "/1rWWgTEDFdV330aLgCoaq7I56lk.jpg",
		"watched": 1,
		"watchedOn": "2021-05-18"
	},
	{
		"id": "tt4504044",
		"title": "The Prodigy",
		"year": 2019,
		"type": "Movie",
		"rating": 6,
		"runtime": 92,
		"genres": [
			"Thriller",
			"Horror",
			"Mystery",
			"Fantasy"
		],
		"directors": [
			"Nicholas McCarthy"
		],
		"posterPath": "/yyejodyk3lWncVjVhhrEkPctY9o.jpg",
		"watched": 1,
		"watchedOn": "2021-05-18"
	},
	{
		"id": "tt5180504",
		"title": "The Witcher",
		"year": 2019,
		"type": "TV Series",
		"rating": 6,
		"runtime": 60,
		"genres": [
			"Adventure",
			"Fantasy",
			"Mystery",
			"Action",
			"Drama"
		],
		"directors": [],
		"posterPath": "/AoGsDM02UVt0npBA8OvpDcZbaMi.jpg",
		"watched": 1,
		"watchedOn": "2022-07-07"
	},
	{
		"id": "tt7242142",
		"title": "Blindspotting",
		"year": 2018,
		"type": "Movie",
		"rating": 6,
		"runtime": 95,
		"genres": [
			"Comedy",
			"Drama",
			"Crime"
		],
		"directors": [
			"Carlos López Estrada"
		],
		"posterPath": "/x4DRZfTqOlmzNWAvy4vcKWkgEGL.jpg",
		"watched": 1,
		"watchedOn": "2021-06-23"
	},
	{
		"id": "tt6499752",
		"title": "Upgrade",
		"year": 2018,
		"type": "Movie",
		"rating": 6,
		"runtime": 100,
		"genres": [
			"Sci-Fi",
			"Thriller",
			"Action"
		],
		"directors": [
			"Leigh Whannell"
		],
		"posterPath": "/woLGROUdPWdBnLVFKYdGD3kFkPY.jpg",
		"watched": 1,
		"watchedOn": "2020-12-03"
	},
	{
		"id": "tt1270797",
		"title": "Venom",
		"year": 2018,
		"type": "Movie",
		"rating": 6,
		"runtime": 112,
		"genres": [
			"Action",
			"Sci-Fi",
			"Adventure"
		],
		"directors": [
			"Ruben Fleischer"
		],
		"posterPath": "/2uNW4WbgBXL25BAbXGLnLqX71Sw.jpg",
		"watched": 1,
		"watchedOn": "2020-12-03"
	},
	{
		"id": "tt3896198",
		"title": "Guardians of the Galaxy: Vol. 2",
		"year": 2017,
		"type": "Movie",
		"rating": 6,
		"runtime": 136,
		"genres": [
			"Action",
			"Sci-Fi",
			"Adventure",
			"Comedy",
			"Fantasy",
			"Music"
		],
		"directors": [
			"James Gunn"
		],
		"posterPath": "/y4MBh0EjBlMuOzv9axM4qJlmhzz.jpg",
		"watched": 1,
		"watchedOn": "2020-12-03"
	},
	{
		"id": "tt6257970",
		"title": "The End of the F***ing World",
		"year": 2017,
		"type": "TV Series",
		"rating": 6,
		"runtime": 25,
		"genres": [
			"Comedy",
			"Drama",
			"Adventure",
			"Romance",
			"Crime",
			"Thriller"
		],
		"directors": [],
		"posterPath": "/f1OV9xEJCZVYcYSDRr5xOD8NJw3.jpg",
		"watched": 1,
		"watchedOn": "2020-12-03"
	},
	{
		"id": "tt1987680",
		"title": "The Upside",
		"year": 2017,
		"type": "Movie",
		"rating": 6,
		"runtime": 126,
		"genres": [
			"Comedy",
			"Drama"
		],
		"directors": [
			"Neil Burger"
		],
		"posterPath": "/hPZ2caow1PCND6qnerfgn6RTXdm.jpg",
		"watched": 1,
		"watchedOn": "2021-08-19"
	},
	{
		"id": "tt3498820",
		"title": "Captain America: Civil War",
		"year": 2016,
		"type": "Movie",
		"rating": 6,
		"runtime": 147,
		"genres": [
			"Action",
			"Sci-Fi"
		],
		"directors": [
			"Anthony Russo",
			"Joe Russo"
		],
		"posterPath": "/rAGiXaUfPzY7CDEyNKUofk3Kw2e.jpg",
		"watched": 1,
		"watchedOn": "2020-12-03"
	},
	{
		"id": "tt2322441",
		"title": "Fifty Shades of Grey",
		"year": 2015,
		"type": "Movie",
		"rating": 6,
		"runtime": 125,
		"genres": [
			"Drama",
			"Romance",
			"Thriller"
		],
		"directors": [
			"Sam Taylor-Johnson"
		],
		"posterPath": "/63kGofUkt1Mx0SIL4XI4Z5AoSgt.jpg",
		"watched": 1,
		"watchedOn": "2025-06-25"
	},
	{
		"id": "tt1843866",
		"title": "Captain America: The Winter Soldier",
		"year": 2014,
		"type": "Movie",
		"rating": 6,
		"runtime": 136,
		"genres": [
			"Action",
			"Adventure",
			"Sci-Fi",
			"Thriller"
		],
		"directors": [
			"Anthony Russo",
			"Joe Russo"
		],
		"posterPath": "/tVFRpFw3xTedgPGqxW0AOI8Qhh0.jpg",
		"watched": 1,
		"watchedOn": "2021-01-27"
	},
	{
		"id": "tt4044364",
		"title": "Citizenfour",
		"year": 2014,
		"type": "Movie",
		"rating": 6,
		"runtime": 114,
		"genres": [
			"Documentary",
			"Biography"
		],
		"directors": [
			"Laura Poitras"
		],
		"posterPath": "/nOVhX69EAxtSKEEnr5UcSd5UVci.jpg",
		"watched": 1,
		"watchedOn": "2022-07-07"
	},
	{
		"id": "tt2084970",
		"title": "The Imitation Game",
		"year": 2014,
		"type": "Movie",
		"rating": 6,
		"runtime": 114,
		"genres": [
			"Drama",
			"Biography",
			"Thriller",
			"War"
		],
		"directors": [
			"Morten Tyldum"
		],
		"posterPath": "/zSqJ1qFq8NXFfi7JeIYMlzyR0dx.jpg",
		"watched": 1,
		"watchedOn": "2023-05-20"
	},
	{
		"id": "tt2866360",
		"title": "Coherence",
		"year": 2013,
		"type": "Movie",
		"rating": 6,
		"runtime": 89,
		"genres": [
			"Sci-Fi",
			"Thriller",
			"Mystery"
		],
		"directors": [
			"James Ward Byrkit"
		],
		"posterPath": "/ezUtb9m5DeLwL2gxi4gktzNCvQv.jpg",
		"watched": 1,
		"watchedOn": "2025-06-27"
	},
	{
		"id": "tt1981115",
		"title": "Thor: The Dark World",
		"year": 2013,
		"type": "Movie",
		"rating": 6,
		"runtime": 112,
		"genres": [
			"Animation",
			"Action",
			"Adventure",
			"Fantasy",
			"Sci-Fi"
		],
		"directors": [
			"Alan Taylor"
		],
		"posterPath": "/wp6OxE4poJ4G7c0U2ZIXasTSMR7.jpg",
		"watched": 1,
		"watchedOn": "2020-12-03"
	},
	{
		"id": "tt0848228",
		"title": "The Avengers",
		"year": 2012,
		"type": "Movie",
		"rating": 6,
		"runtime": 143,
		"genres": [
			"Action",
			"Sci-Fi"
		],
		"directors": [
			"Joss Whedon"
		],
		"posterPath": "/RYMX2wcKCBAr24UyPD7xwmjaTn.jpg",
		"watched": 1,
		"watchedOn": "2021-04-06"
	},
	{
		"id": "tt1695360",
		"title": "The Legend of Korra",
		"year": 2012,
		"type": "TV Series",
		"rating": 6,
		"runtime": 23,
		"genres": [
			"Animation",
			"Action",
			"Adventure",
			"Fantasy",
			"Family",
			"Sci-Fi"
		],
		"directors": [],
		"posterPath": "/dZgYvSfuh1YHDrJuILlVQ5oA2hF.jpg",
		"watched": 1,
		"watchedOn": "2021-03-26"
	},
	{
		"id": "tt1259521",
		"title": "The Cabin in the Woods",
		"year": 2011,
		"type": "Movie",
		"rating": 6,
		"runtime": 95,
		"genres": [
			"Horror",
			"Mystery",
			"Thriller"
		],
		"directors": [
			"Drew Goddard"
		],
		"posterPath": "/zZZe5wn0udlhMtdlDjN4NB72R6e.jpg",
		"watched": 1,
		"watchedOn": "2021-05-20"
	},
	{
		"id": "tt0371746",
		"title": "Iron Man",
		"year": 2008,
		"type": "Movie",
		"rating": 6,
		"runtime": 126,
		"genres": [
			"Action",
			"Sci-Fi",
			"Adventure"
		],
		"directors": [
			"Jon Favreau"
		],
		"posterPath": "/78lPtwv72eTNqFW9COBYI0dWDJa.jpg",
		"watched": 1,
		"watchedOn": "2022-07-07"
	},
	{
		"id": "tt0497465",
		"title": "Vicky Cristina Barcelona",
		"year": 2008,
		"type": "Movie",
		"rating": 6,
		"runtime": 96,
		"genres": [
			"Drama",
			"Romance",
			"Comedy"
		],
		"directors": [
			"Woody Allen"
		],
		"posterPath": "/ekAIg0GSbbHTH7y1GPgWj0brLTW.jpg",
		"watched": 1,
		"watchedOn": "2025-02-08"
	},
	{
		"id": "tt0120744",
		"title": "The Man in the Iron Mask",
		"year": 1998,
		"type": "Movie",
		"rating": 6,
		"runtime": 132,
		"genres": [
			"Drama",
			"Adventure",
			"Action"
		],
		"directors": [
			"Randall Wallace"
		],
		"posterPath": "/zHE9yRURvA7DyhYtQxkGTfE1Ywi.jpg",
		"watched": 1,
		"watchedOn": "2021-06-22"
	},
	{
		"id": "tt3228774",
		"title": "Cruella",
		"year": 2021,
		"type": "Movie",
		"rating": 5,
		"runtime": 134,
		"genres": [
			"Comedy",
			"Crime",
			"Drama",
			"Adventure"
		],
		"directors": [
			"Craig Gillespie"
		],
		"posterPath": "/hjS9mH8KvRiGHgjk6VUZH7OT0Ng.jpg",
		"watched": 1,
		"watchedOn": "2021-07-31"
	},
	{
		"id": "tt6264654",
		"title": "Free Guy",
		"year": 2021,
		"type": "Movie",
		"rating": 5,
		"runtime": 115,
		"genres": [
			"Action",
			"Comedy",
			"Sci-Fi",
			"Adventure",
			"Fantasy",
			"Romance"
		],
		"directors": [
			"Shawn Levy"
		],
		"posterPath": "/dxraF0qPr1OEgJk17ltQTO84kQF.jpg",
		"watched": 1,
		"watchedOn": "2022-07-07"
	},
	{
		"id": "tt8385148",
		"title": "Hitman's Wife's Bodyguard",
		"year": 2021,
		"type": "Movie",
		"rating": 5,
		"runtime": 100,
		"genres": [
			"Action",
			"Comedy",
			"Thriller",
			"Crime",
			"Romance",
			"Adventure",
			"Drama"
		],
		"directors": [
			"Patrick Hughes"
		],
		"posterPath": "/6zwGWDpY8Zu0L6W4SYWERBR8Msw.jpg",
		"watched": 1,
		"watchedOn": "2021-07-13"
	},
	{
		"id": "tt6902332",
		"title": "The Marksman",
		"year": 2021,
		"type": "Movie",
		"rating": 5,
		"runtime": 108,
		"genres": [
			"Drama",
			"Thriller",
			"Action"
		],
		"directors": [
			"Robert Lorenz"
		],
		"posterPath": "/6vcDalR50RWa309vBH1NLmG2rjQ.jpg",
		"watched": 1,
		"watchedOn": "2021-05-28"
	},
	{
		"id": "tt8332922",
		"title": "A Quiet Place Part II",
		"year": 2020,
		"type": "Movie",
		"rating": 5,
		"runtime": 97,
		"genres": [
			"Drama",
			"Thriller",
			"Sci-Fi",
			"Horror"
		],
		"directors": [
			"John Krasinski"
		],
		"posterPath": "/4q2hz2m8hubgvijz8Ez0T2Os2Yv.jpg",
		"watched": 1,
		"watchedOn": "2021-06-15"
	},
	{
		"id": "tt2304589",
		"title": "Defending Jacob",
		"year": 2020,
		"type": "TV Mini Series",
		"rating": 5,
		"runtime": 50,
		"genres": [
			"Mystery",
			"Thriller",
			"Drama",
			"Crime"
		],
		"directors": [],
		"posterPath": "/JTmkzwSDRiS9nvSPwpDB9fmZj2.jpg",
		"watched": 1,
		"watchedOn": "2021-05-12"
	},
	{
		"id": "tt1051906",
		"title": "The Invisible Man",
		"year": 2020,
		"type": "Movie",
		"rating": 5,
		"runtime": 124,
		"genres": [
			"Sci-Fi",
			"Thriller",
			"Horror",
			"Mystery",
			"Drama"
		],
		"directors": [
			"Leigh Whannell"
		],
		"posterPath": "/5EufsDwXdY2CVttYOk2WtYhgKpa.jpg",
		"watched": 1,
		"watchedOn": "2023-07-13"
	},
	{
		"id": "tt4154796",
		"title": "Avengers: Endgame",
		"year": 2019,
		"type": "Movie",
		"rating": 5,
		"runtime": 181,
		"genres": [
			"Action",
			"Sci-Fi",
			"Adventure"
		],
		"directors": [
			"Anthony Russo",
			"Joe Russo"
		],
		"posterPath": "/ulzhLuWrPK07P1YkdWQLZnQh1JL.jpg",
		"watched": 1,
		"watchedOn": "2022-04-21"
	},
	{
		"id": "tt0489974",
		"title": "Carnival Row",
		"year": 2019,
		"type": "TV Series",
		"rating": 5,
		"runtime": 56,
		"genres": [
			"Fantasy",
			"Mystery",
			"Thriller",
			"Crime",
			"Drama"
		],
		"directors": [],
		"posterPath": "/jyhxT10e2z9IDsKoIQDKhyxSQJt.jpg",
		"watched": 1,
		"watchedOn": "2021-06-23"
	},
	{
		"id": "tt5886046",
		"title": "Escape Room",
		"year": 2019,
		"type": "Movie",
		"rating": 5,
		"runtime": 99,
		"genres": [
			"Thriller",
			"Action",
			"Adventure",
			"Mystery",
			"Horror",
			"Sci-Fi"
		],
		"directors": [
			"Adam Robitel"
		],
		"posterPath": "/8Ls1tZ6qjGzfGHjBB7ihOnf7f0b.jpg",
		"watched": 1,
		"watchedOn": "2020-12-03"
	},
	{
		"id": "tt1082807",
		"title": "The Belko Experiment",
		"year": 2016,
		"type": "Movie",
		"rating": 5,
		"runtime": 89,
		"genres": [
			"Horror",
			"Thriller",
			"Action"
		],
		"directors": [
			"Greg McLean"
		],
		"posterPath": "/faJK0dP3S92kQoKtO4LZMjy41kf.jpg",
		"watched": 1,
		"watchedOn": "2021-01-27"
	},
	{
		"id": "tt0478970",
		"title": "Ant-Man",
		"year": 2015,
		"type": "Movie",
		"rating": 5,
		"runtime": 117,
		"genres": [
			"Action",
			"Sci-Fi",
			"Comedy"
		],
		"directors": [
			"Peyton Reed"
		],
		"posterPath": "/rQRnQfUl3kfp78nCWq8Ks04vnq1.jpg",
		"watched": 1,
		"watchedOn": "2021-01-27"
	},
	{
		"id": "tt1300854",
		"title": "Iron Man 3",
		"year": 2013,
		"type": "Movie",
		"rating": 5,
		"runtime": 130,
		"genres": [
			"Action",
			"Adventure",
			"Sci-Fi"
		],
		"directors": [
			"Shane Black"
		],
		"posterPath": "/qhPtAc1TKbMPqNvcdXSOn9Bn7hZ.jpg",
		"watched": 1,
		"watchedOn": "2020-12-03"
	},
	{
		"id": "tt0458339",
		"title": "Captain America: The First Avenger",
		"year": 2011,
		"type": "Movie",
		"rating": 5,
		"runtime": 124,
		"genres": [
			"Action",
			"Adventure",
			"Sci-Fi"
		],
		"directors": [
			"Joe Johnston"
		],
		"posterPath": "/vSNxAJTlD0r02V9sPYpOjqDZXUK.jpg",
		"watched": 1,
		"watchedOn": "2022-07-07"
	},
	{
		"id": "tt1778304",
		"title": "Paranormal Activity 3",
		"year": 2011,
		"type": "Movie",
		"rating": 5,
		"runtime": 83,
		"genres": [
			"Horror",
			"Mystery",
			"Thriller"
		],
		"directors": [
			"Henry Joost",
			"Ariel Schulman"
		],
		"posterPath": "/9nYranPiWdNmbD5PRPPSL7VUFTS.jpg",
		"watched": 1,
		"watchedOn": "2021-01-27"
	},
	{
		"id": "tt1228705",
		"title": "Iron Man 2",
		"year": 2010,
		"type": "Movie",
		"rating": 5,
		"runtime": 124,
		"genres": [
			"Action",
			"Sci-Fi"
		],
		"directors": [
			"Jon Favreau"
		],
		"posterPath": "/6WBeq4fCfn7AN0o21W9qNcRF2l9.jpg",
		"watched": 1,
		"watchedOn": "2020-12-03"
	},
	{
		"id": "tt1148204",
		"title": "Orphan",
		"year": 2009,
		"type": "Movie",
		"rating": 5,
		"runtime": 123,
		"genres": [
			"Thriller",
			"Mystery",
			"Horror"
		],
		"directors": [
			"Jaume Collet-Serra"
		],
		"posterPath": "/lCGpOgoTOGLtZnBiGY9HRg5Xnjd.jpg",
		"watched": 1,
		"watchedOn": "2020-12-03"
	},
	{
		"id": "tt1649418",
		"title": "The Gray Man",
		"year": 2022,
		"type": "Movie",
		"rating": 4,
		"runtime": 122,
		"genres": [
			"Thriller",
			"Mystery",
			"Action"
		],
		"directors": [
			"Joe Russo",
			"Anthony Russo"
		],
		"posterPath": "/8cXbitsS6dWQ5gfMTZdorpAAzEH.jpg",
		"watched": 1,
		"watchedOn": "2025-06-23"
	},
	{
		"id": "tt3480822",
		"title": "Black Widow",
		"year": 2021,
		"type": "Movie",
		"rating": 4,
		"runtime": 134,
		"genres": [
			"Action",
			"Adventure",
			"Sci-Fi"
		],
		"directors": [
			"Cate Shortland"
		],
		"posterPath": "/qAZ0pzat24kLdO3o8ejmbLxyOac.jpg",
		"watched": 1,
		"watchedOn": "2021-07-25"
	},
	{
		"id": "tt10872600",
		"title": "Spider-Man: No Way Home",
		"year": 2021,
		"type": "Movie",
		"rating": 4,
		"runtime": 148,
		"genres": [
			"Action",
			"Adventure",
			"Sci-Fi",
			"Fantasy"
		],
		"directors": [
			"Jon Watts"
		],
		"posterPath": "/1g0dhYtq4irTY1GPXvft6k4YLjm.jpg",
		"watched": 1,
		"watchedOn": "2021-12-18"
	},
	{
		"id": "tt7097896",
		"title": "Venom: Let There Be Carnage",
		"year": 2021,
		"type": "Movie",
		"rating": 4,
		"runtime": 97,
		"genres": [
			"Animation",
			"Action",
			"Thriller",
			"Sci-Fi",
			"Adventure",
			"Fantasy",
			"Horror",
			"Crime"
		],
		"directors": [
			"Andy Serkis"
		],
		"posterPath": "/pzKsRuKLFmYrW5Q0q8E8G78Tcgo.jpg",
		"watched": 1,
		"watchedOn": "2021-10-17"
	},
	{
		"id": "tt7550000",
		"title": "Project Power",
		"year": 2020,
		"type": "Movie",
		"rating": 4,
		"runtime": 113,
		"genres": [
			"Thriller",
			"Sci-Fi",
			"Action",
			"Crime"
		],
		"directors": [
			"Henry Joost",
			"Ariel Schulman"
		],
		"posterPath": "/TnOeov4w0sTtV2gqICqIxVi74V.jpg",
		"watched": 1,
		"watchedOn": "2020-12-03"
	},
	{
		"id": "tt11448214",
		"title": "Rent-a-Girlfriend",
		"year": 2020,
		"type": "TV Series",
		"rating": 4,
		"runtime": 24,
		"genres": [
			"Animation",
			"Comedy",
			"Romance"
		],
		"directors": [],
		"posterPath": "/6ZpDPUNtVw6UdJoStvVlRZ62yAi.jpg",
		"watched": 1,
		"watchedOn": "2022-07-07"
	},
	{
		"id": "tt7456310",
		"title": "Anna",
		"year": 2019,
		"type": "Movie",
		"rating": 4,
		"runtime": 118,
		"genres": [
			"Action",
			"Thriller",
			"Adventure",
			"Drama"
		],
		"directors": [
			"Luc Besson"
		],
		"posterPath": "/2U0oAVAE0lDRhNmJPPYhDW9kQ8t.jpg",
		"watched": 1,
		"watchedOn": "2021-02-18"
	},
	{
		"id": "tt8772296",
		"title": "Euphoria",
		"year": 2019,
		"type": "TV Series",
		"rating": 4,
		"runtime": 60,
		"genres": [
			"Drama"
		],
		"directors": [],
		"posterPath": "/aJrG7OkoTMPWG5c8opz8a93AZPY.jpg",
		"watched": 1,
		"watchedOn": "2022-07-07"
	},
	{
		"id": "tt9354944",
		"title": "Jexi",
		"year": 2019,
		"type": "Movie",
		"rating": 4,
		"runtime": 84,
		"genres": [
			"Comedy",
			"Romance",
			"Sci-Fi"
		],
		"directors": [
			"Jon Lucas",
			"Scott Moore"
		],
		"posterPath": "/sizYjc8lAFStRZXtI1uRBDsOTt6.jpg",
		"watched": 1,
		"watchedOn": "2020-12-03"
	},
	{
		"id": "tt6857112",
		"title": "Us",
		"year": 2019,
		"type": "Movie",
		"rating": 4,
		"runtime": 116,
		"genres": [
			"Thriller",
			"Horror",
			"Mystery"
		],
		"directors": [
			"Jordan Peele"
		],
		"posterPath": "/ux2dU1jQ2ACIMShzB3yP93Udpzc.jpg",
		"watched": 1,
		"watchedOn": "2020-12-03"
	},
	{
		"id": "tt6315640",
		"title": "Atypical",
		"year": 2017,
		"type": "TV Series",
		"rating": 4,
		"runtime": 30,
		"genres": [
			"Comedy",
			"Drama"
		],
		"directors": [],
		"posterPath": "/kNif3eZAjQ7qU3Ol9E7zo0kjPMo.jpg",
		"watched": 1,
		"watchedOn": "2021-03-26"
	},
	{
		"id": "tt2250912",
		"title": "Spider-Man: Homecoming",
		"year": 2017,
		"type": "Movie",
		"rating": 4,
		"runtime": 133,
		"genres": [
			"Action",
			"Sci-Fi",
			"Adventure"
		],
		"directors": [
			"Jon Watts"
		],
		"posterPath": "/c24sv2weTHPsmDa7jEMN0m2P3RT.jpg",
		"watched": 1,
		"watchedOn": "2020-12-03"
	},
	{
		"id": "tt3173594",
		"title": "Hacker",
		"year": 2016,
		"type": "Movie",
		"rating": 4,
		"runtime": 95,
		"genres": [
			"Crime",
			"Thriller",
			"Drama"
		],
		"directors": [
			"Akan Satayev"
		],
		"posterPath": "/gpYwKrP6s749b5Nzgm2174jKrpf.jpg",
		"watched": 1,
		"watchedOn": "2020-12-03"
	},
	{
		"id": "tt0295297",
		"title": "Harry Potter and the Chamber of Secrets",
		"year": 2002,
		"type": "Movie",
		"rating": 4,
		"runtime": 161,
		"genres": [
			"Mystery",
			"Family",
			"Adventure",
			"Fantasy"
		],
		"directors": [
			"Chris Columbus"
		],
		"posterPath": "/sdEOH0992YZ0QSxgXNIGLq1ToUi.jpg",
		"watched": 1,
		"watchedOn": "2021-04-07"
	},
	{
		"id": "tt9844522",
		"title": "Escape Room: Tournament of Champions",
		"year": 2021,
		"type": "Movie",
		"rating": 3,
		"runtime": 88,
		"genres": [
			"Mystery",
			"Thriller",
			"Horror",
			"Action",
			"Adventure",
			"Sci-Fi"
		],
		"directors": [
			"Adam Robitel"
		],
		"posterPath": "/jGYJyPzVgrVV2bgClI9uvEZgVLE.jpg",
		"watched": 1,
		"watchedOn": "2021-07-21"
	},
	{
		"id": "tt0870154",
		"title": "Jungle Cruise",
		"year": 2021,
		"type": "Movie",
		"rating": 3,
		"runtime": 127,
		"genres": [
			"Adventure",
			"Fantasy",
			"Action",
			"Comedy"
		],
		"directors": [
			"Jaume Collet-Serra"
		],
		"posterPath": "/yKy9ELL8CON5sqDg4yIvBb5LTZL.jpg",
		"watched": 1,
		"watchedOn": "2021-07-29"
	},
	{
		"id": "tt0293429",
		"title": "Mortal Kombat",
		"year": 2021,
		"type": "Movie",
		"rating": 3,
		"runtime": 110,
		"genres": [
			"Thriller",
			"Sci-Fi",
			"Adventure",
			"Fantasy",
			"Action"
		],
		"directors": [
			"Simon McQuoid"
		],
		"posterPath": "/ybrX94xQm8lXYpZAPRmwD9iIbWP.jpg",
		"watched": 1,
		"watchedOn": "2021-04-23"
	},
	{
		"id": "tt10342730",
		"title": "Spiral",
		"year": 2021,
		"type": "Movie",
		"rating": 3,
		"runtime": 93,
		"genres": [
			"Horror",
			"Mystery",
			"Thriller",
			"Crime",
			"Drama"
		],
		"directors": [
			"Darren Lynn Bousman"
		],
		"posterPath": "/cTvSDfBuXTZTdRCNduGMANd7VEP.jpg",
		"watched": 1,
		"watchedOn": "2021-07-31"
	},
	{
		"id": "tt11804152",
		"title": "Till Death",
		"year": 2021,
		"type": "Movie",
		"rating": 3,
		"runtime": 91,
		"genres": [
			"Thriller",
			"Horror"
		],
		"directors": [
			"S.K. Dale"
		],
		"posterPath": "/bvwMvrX2XqZVOz35YuYbFx3Iggr.jpg",
		"watched": 1,
		"watchedOn": "2021-09-03"
	},
	{
		"id": "tt4154664",
		"title": "Captain Marvel",
		"year": 2019,
		"type": "Movie",
		"rating": 3,
		"runtime": 123,
		"genres": [
			"Action",
			"Adventure",
			"Sci-Fi"
		],
		"directors": [
			"Anna Boden",
			"Ryan Fleck"
		],
		"posterPath": "/AtsgWhDnHTq68L0lLsUrCnM7TjG.jpg",
		"watched": 1,
		"watchedOn": "2020-12-03"
	},
	{
		"id": "tt5734576",
		"title": "The Possession of Hannah Grace",
		"year": 2018,
		"type": "Movie",
		"rating": 3,
		"runtime": 86,
		"genres": [
			"Horror",
			"Mystery",
			"Thriller"
		],
		"directors": [
			"Diederik Van Rooijen"
		],
		"posterPath": "/hDDb0H0uJp2wjoJBbBHbKlYRbug.jpg",
		"watched": 1,
		"watchedOn": "2020-12-03"
	},
	{
		"id": "tt1396484",
		"title": "It",
		"year": 2017,
		"type": "Movie",
		"rating": 3,
		"runtime": 135,
		"genres": [
			"Horror"
		],
		"directors": [
			"Andy Muschietti"
		],
		"posterPath": "/9E2y5Q7WlCVNEhP5GiVTjhEhx1o.jpg",
		"watched": 1,
		"watchedOn": "2021-03-26"
	},
	{
		"id": "tt0803096",
		"title": "Warcraft",
		"year": 2016,
		"type": "Movie",
		"rating": 3,
		"runtime": 123,
		"genres": [
			"Animation",
			"Action",
			"Adventure",
			"Fantasy"
		],
		"directors": [
			"Duncan Jones"
		],
		"posterPath": "/eGi5aoxaZveqNLtE7BZJCuWwR3G.jpg",
		"watched": 1,
		"watchedOn": "2022-07-07"
	},
	{
		"id": "tt1956620",
		"title": "Sex Tape",
		"year": 2014,
		"type": "Movie",
		"rating": 3,
		"runtime": 94,
		"genres": [
			"Comedy",
			"Romance"
		],
		"directors": [
			"Jake Kasdan"
		],
		"posterPath": "/u2h7UnSHrbAA5WBoKhdH1rlDZfz.jpg",
		"watched": 1,
		"watchedOn": "2021-05-20"
	},
	{
		"id": "tt0241527",
		"title": "Harry Potter and the Sorcerer's Stone",
		"year": 2001,
		"type": "Movie",
		"rating": 3,
		"runtime": 152,
		"genres": [
			"Family",
			"Adventure",
			"Fantasy"
		],
		"directors": [
			"Chris Columbus"
		],
		"posterPath": "/wuMc08IPKEatf9rnMNXvIDxqP4W.jpg",
		"watched": 1,
		"watchedOn": "2021-03-26"
	},
	{
		"id": "tt10954652",
		"title": "Old",
		"year": 2021,
		"type": "Movie",
		"rating": 2,
		"runtime": 108,
		"genres": [
			"Thriller",
			"Drama",
			"Mystery"
		],
		"directors": [
			"M. Night Shyamalan"
		],
		"posterPath": "/vclShucpUmPhdAOmKgf3B3Z4POD.jpg",
		"watched": 1,
		"watchedOn": "2021-08-12"
	},
	{
		"id": "tt7069210",
		"title": "The Conjuring: The Devil Made Me Do It",
		"year": 2021,
		"type": "Movie",
		"rating": 2,
		"runtime": 112,
		"genres": [
			"Horror",
			"Mystery",
			"Thriller"
		],
		"directors": [
			"Michael Chaves"
		],
		"posterPath": "/xbSuFiJbbBWCkyCCKIMfuDCA4yV.jpg",
		"watched": 1,
		"watchedOn": "2021-06-06"
	},
	{
		"id": "tt6334354",
		"title": "The Suicide Squad",
		"year": 2021,
		"type": "Movie",
		"rating": 2,
		"runtime": 132,
		"genres": [
			"Action",
			"Adventure",
			"Sci-Fi",
			"Comedy"
		],
		"directors": [
			"James Gunn"
		],
		"posterPath": "/q61qEyssk2ku3okWICKArlAdhBn.jpg",
		"watched": 1,
		"watchedOn": "2021-12-16"
	},
	{
		"id": "tt8155288",
		"title": "Happy Death Day 2U",
		"year": 2019,
		"type": "Movie",
		"rating": 2,
		"runtime": 100,
		"genres": [
			"Horror",
			"Mystery",
			"Thriller",
			"Comedy",
			"Sci-Fi"
		],
		"directors": [
			"Christopher Landon"
		],
		"posterPath": "/4tdnePOkOOzwuGPEOAHp8UA4vqx.jpg",
		"watched": 1,
		"watchedOn": "2022-07-07"
	},
	{
		"id": "tt0938283",
		"title": "The Last Airbender",
		"year": 2010,
		"type": "Movie",
		"rating": 1,
		"runtime": 103,
		"genres": [
			"Adventure",
			"Family",
			"Fantasy",
			"Action"
		],
		"directors": [
			"M. Night Shyamalan"
		],
		"posterPath": "/kl9JJ8288bNsY8oqT1SpQh1w2mb.jpg",
		"watched": 1,
		"watchedOn": "2021-06-08"
	}
];
