import antfu from '@antfu/eslint-config'

export default antfu(
	{
		svelte: true,
		formatters: true,
		// The repo has been tab-indented since day one; ESLint can't re-indent
		// Svelte markup, so converting to spaces isn't worth the churn.
		stylistic: { indent: 'tab' },
		// The tasting scratch files are git-ignored only via .git/info/exclude,
		// which the gitignore integration doesn't read; keep repo-wide runs
		// (and their --fix) away from work-in-progress harnesses.
		// painting-sizes.json is generated by scripts/generate-painting-sizes.ts;
		// letting --fix collapse its arrays just churns against the generator.
		ignores: [
			'static/**',
			'painting-tasting/**',
			'*-tasting.html',
			'src/lib/painting-sizes.json',
		],
	},
	{
		rules: {
			// Prettier wrapped long values as tab indentation + space alignment;
			// smart-tabs accepts that instead of re-wrapping the whole repo.
			'style/no-mixed-spaces-and-tabs': ['error', 'smart-tabs'],
		},
	},
	{
		files: ['**/*.svelte'],
		rules: {
			// This site deploys at the domain root with no base path, so wrapping
			// every href in resolve() buys nothing and costs readability.
			'svelte/no-navigation-without-resolve': 'off',
			// Handlers in one section reference runes state declared in a later
			// section; TS still reports any real use-before-init.
			'no-use-before-define': 'off',
		},
	},
	{
		// antfu's svelte block covers *.svelte.ts too and hands indentation to
		// svelte/indent, which only reads markup: rune modules end up with no
		// indent rule at all. Put the plain one back.
		files: ['**/*.svelte.js', '**/*.svelte.ts'],
		rules: {
			'style/indent': ['error', 'tab'],
		},
	},
)
