name = "khaledwaleed"
main = "build/index.js"
type = "javascript"
compatibility_date = "2025-05-31"

[env.production]
name = "khaledwaleed-production"
route = "khaledwaleed.com/*"

[build]
command = "bun run build"
cwd = "."
watch_paths = ["src/**"]

[build.upload]
format = "service-worker"
