#!/usr/bin/env bun
/**
 * Build src/lib/films.ts from an IMDb ratings export CSV.
 *
 * Usage:  bun run scripts/build-films.ts [path-to-csv]
 * Default CSV path: scripts/imdb-ratings.csv
 *
 * Re-run whenever you export a fresh ratings.csv from IMDb
 * (Your Ratings → ⋯ → Export).
 */
import { readFileSync, writeFileSync } from 'node:fs';
import path from 'node:path';

const CSV_PATH = path.resolve(process.argv[2] ?? 'scripts/imdb-ratings.csv');
const OUT_PATH = path.resolve('src/lib/films.ts');

/** Minimal RFC-4180 CSV parser (handles quoted fields, commas, "" escapes). */
function parseCsv(text: string): string[][] {
	const rows: string[][] = [];
	let row: string[] = [];
	let field = '';
	let inQuotes = false;

	for (let i = 0; i < text.length; i++) {
		const c = text[i];
		if (inQuotes) {
			if (c === '"') {
				if (text[i + 1] === '"') {
					field += '"';
					i++;
				} else {
					inQuotes = false;
				}
			} else {
				field += c;
			}
		} else if (c === '"') {
			inQuotes = true;
		} else if (c === ',') {
			row.push(field);
			field = '';
		} else if (c === '\n' || c === '\r') {
			if (c === '\r' && text[i + 1] === '\n') i++;
			row.push(field);
			field = '';
			if (row.length > 1 || row[0] !== '') rows.push(row);
			row = [];
		} else {
			field += c;
		}
	}
	if (field !== '' || row.length) {
		row.push(field);
		if (row.length > 1 || row[0] !== '') rows.push(row);
	}
	return rows;
}

const splitList = (s: string): string[] =>
	s
		.split(',')
		.map((x) => x.trim())
		.filter(Boolean);

const raw = readFileSync(CSV_PATH, 'utf8');
const table = parseCsv(raw);
if (!table.length) throw new Error(`No rows parsed from ${CSV_PATH}`);

const header = table[0];
const col = (name: string) => {
	const idx = header.indexOf(name);
	if (idx === -1) throw new Error(`Missing column "${name}" in ${CSV_PATH}`);
	return idx;
};

const C = {
	id: col('Const'),
	rating: col('Your Rating'),
	rated: col('Date Rated'),
	title: col('Title'),
	url: col('URL'),
	type: col('Title Type'),
	imdb: col('IMDb Rating'),
	runtime: col('Runtime (mins)'),
	year: col('Year'),
	genres: col('Genres'),
	directors: col('Directors')
};

type Film = {
	id: string;
	title: string;
	year: number;
	type: string;
	rating: number;
	imdbRating: number;
	runtime: number | null;
	genres: string[];
	directors: string[];
	rated: string;
	url: string;
	watched: number;
};

// Times watched, keyed by IMDb const. Not part of the IMDb export, so it lives
// here and survives regeneration. Anything not listed defaults to 1.
const REWATCHES: Record<string, number> = {
	tt0417299: 5, // Avatar: The Last Airbender
	tt5363918: 3, // Disenchantment
	tt0468569: 2, // The Dark Knight
	tt0120737: 3, // LOTR: The Fellowship of the Ring
	tt0167261: 3, // LOTR: The Two Towers
	tt0167260: 3, // LOTR: The Return of the King
	tt1856101: 2 // Blade Runner 2049
};

const films: Film[] = table.slice(1).map((r) => {
	const runtime = parseInt(r[C.runtime], 10);
	const imdbRating = parseFloat(r[C.imdb]);
	const id = r[C.id];
	return {
		id,
		title: r[C.title],
		year: parseInt(r[C.year], 10) || 0,
		type: r[C.type],
		rating: parseInt(r[C.rating], 10) || 0,
		imdbRating: Number.isFinite(imdbRating) ? imdbRating : 0,
		runtime: Number.isFinite(runtime) ? runtime : null,
		genres: splitList(r[C.genres]),
		directors: splitList(r[C.directors]),
		rated: r[C.rated],
		url: r[C.url],
		watched: REWATCHES[id] ?? 1
	};
});

// Highest personal rating first, then newest, then alphabetical.
films.sort((a, b) => b.rating - a.rating || b.year - a.year || a.title.localeCompare(b.title));

const body = `// AUTO-GENERATED by scripts/build-films.ts — do not edit by hand.
// Source: IMDb ratings export. Regenerate: bun run scripts/build-films.ts [csv]
// ${films.length} titles · generated ${new Date().toISOString().slice(0, 10)}

export type TitleType =
	| 'Movie'
	| 'TV Series'
	| 'TV Mini Series'
	| 'Short'
	| 'TV Movie'
	| (string & {});

export interface Film {
	/** IMDb const, e.g. tt0166924 */
	id: string;
	title: string;
	year: number;
	type: TitleType;
	/** Personal rating, 1–10 */
	rating: number;
	/** Public IMDb rating */
	imdbRating: number;
	/** Runtime in minutes, when known */
	runtime: number | null;
	genres: string[];
	directors: string[];
	/** Date rated, ISO yyyy-mm-dd */
	rated: string;
	url: string;
	/** Times watched (default 1) */
	watched: number;
}

export const films: Film[] = [
${films.map((f) => '\t' + JSON.stringify(f)).join(',\n')}
];
`;

writeFileSync(OUT_PATH, body);
console.log(`✓ wrote ${films.length} films → ${path.relative(process.cwd(), OUT_PATH)}`);
