#!/usr/bin/env bun
/**
 * Resolve each title in src/lib/films.ts to its TMDB poster_path and write
 * src/lib/posters.ts (a map of IMDb const → poster_path). Images themselves
 * are NOT downloaded — they are hotlinked from image.tmdb.org at render time.
 *
 * Requires TMDB_API_KEY in .env (Bun loads it automatically).
 * Run: bun run scripts/fetch-posters.ts
 *
 * Attribution: this product uses the TMDB API but is not endorsed or
 * certified by TMDB.
 */
import { writeFile } from 'node:fs/promises';
import path from 'node:path';
import { films } from '../src/lib/films';

const API_KEY = process.env.TMDB_API_KEY;
if (!API_KEY) {
	console.error('✗ TMDB_API_KEY missing. Add it to .env (see .env.example).');
	process.exit(1);
}

const DATA_OUT = path.resolve('src/lib/posters.ts');
const CONCURRENCY = 8;

type FindResult = {
	movie_results?: { poster_path: string | null }[];
	tv_results?: { poster_path: string | null }[];
};

async function posterPathFor(imdbId: string, isMovie: boolean): Promise<string | null> {
	const url = `https://api.themoviedb.org/3/find/${imdbId}?external_source=imdb_id&api_key=${API_KEY}`;
	const res = await fetch(url, { headers: { Accept: 'application/json' } });
	if (!res.ok) throw new Error(`find ${imdbId} → ${res.status}`);
	const json = (await res.json()) as FindResult;
	const primary = isMovie ? json.movie_results : json.tv_results;
	const fallback = isMovie ? json.tv_results : json.movie_results;
	return primary?.[0]?.poster_path ?? fallback?.[0]?.poster_path ?? null;
}

const paths: Record<string, string> = {};
let none = 0;
let errors = 0;

async function handle(film: (typeof films)[number]) {
	try {
		const isMovie = film.type === 'Movie' || film.type === 'TV Movie';
		const poster = await posterPathFor(film.id, isMovie);
		if (!poster) {
			console.warn(`  – no poster: ${film.title} (${film.id})`);
			none++;
			return;
		}
		paths[film.id] = poster;
	} catch (e) {
		console.error(`  ✗ ${film.title}: ${(e as Error).message}`);
		errors++;
	}
}

/** Simple fixed-size concurrency pool. */
async function pool<T>(items: T[], size: number, fn: (item: T) => Promise<void>) {
	let i = 0;
	const workers = Array.from({ length: size }, async () => {
		while (i < items.length) await fn(items[i++]);
	});
	await Promise.all(workers);
}

async function main() {
	console.log(`Resolving poster paths for ${films.length} titles (concurrency ${CONCURRENCY})…`);
	await pool(films, CONCURRENCY, handle);

	const entries = Object.entries(paths).sort(([a], [b]) => a.localeCompare(b));
	const body = `// AUTO-GENERATED by scripts/fetch-posters.ts — do not edit by hand.
// IMDb const → TMDB poster_path. Images are hotlinked from image.tmdb.org.
// Posters via the TMDB API (not endorsed or certified by TMDB).
// ${entries.length} posters · generated ${new Date().toISOString().slice(0, 10)}

export const posterPaths: Record<string, string> = {
${entries.map(([id, p]) => `\t'${id}': '${p}'`).join(',\n')}
};
`;
	await writeFile(DATA_OUT, body);
	console.log(
		`\nDone — ${entries.length} resolved, ${none} no-poster, ${errors} errors.` +
			`\n✓ wrote ${path.relative(process.cwd(), DATA_OUT)}`
	);
}

main();
