#!/usr/bin/env node
/**
 * Pin the display face to one weight.
 *
 * The museum only ever sets Newsreader at one weight (every `--font-display`
 * rule, `.prose-romantic strong` included), yet the fontsource file carries
 * wght 200-800 deltas, downloaded on every page ahead of the hero
 * painting. Pinning wght and leaving opsz variable more than halves both
 * faces (128.9K → 58.1K roman, 143.4K → 64.1K italic) with the optical
 * size still live.
 *
 * Coverage and unicode-ranges are read out of fontsource's own CSS, so the
 * emitted faces declare exactly what they replace. Re-run after bumping
 * @fontsource-variable/newsreader:
 *   node scripts/generate-fonts.ts
 */
import { mkdir, readFile, writeFile } from 'node:fs/promises'
import path from 'node:path'
import subsetFont from 'subset-font'

const SRC = path.resolve('node_modules/@fontsource-variable/newsreader')
const OUT = path.resolve('src/lib/fonts')
const STYLESHEET = path.join(OUT, 'newsreader.css')
const WEIGHT = 500

interface Face {
	file: string
	style: 'normal' | 'italic'
	unicodeRange: string
}

function readFaces(css: string): Face[] {
	const faces: Face[] = []
	for (const block of css.split('@font-face').slice(1)) {
		const file = block.match(/url\(\.\/files\/([\w-]+\.woff2)\)/)?.[1]
		const style = block.match(/font-style:\s*(normal|italic)/)?.[1]
		const unicodeRange = block.match(/unicode-range:([^;]+);/)?.[1]
		if (!file || !style || !unicodeRange)
			throw new Error(`unparsable @font-face:\n@font-face${block}`)
		faces.push({ file, style: style as Face['style'], unicodeRange: unicodeRange.trim() })
	}
	return faces
}

// hb-subset keeps glyphs by codepoint, so the declared range becomes the
// text to retain; codepoints the font never had are simply absent.
function expand(unicodeRange: string): string {
	let text = ''
	for (const part of unicodeRange.split(',')) {
		const [from, to] = part.trim().replace(/^U\+/i, '').split('-')
		const start = Number.parseInt(from, 16)
		const end = to ? Number.parseInt(to, 16) : start
		for (let cp = start; cp <= end; cp++)
			text += String.fromCodePoint(cp)
	}
	return text
}

await mkdir(OUT, { recursive: true })

const faces = [
	...readFaces(await readFile(path.join(SRC, 'opsz.css'), 'utf8')),
	...readFaces(await readFile(path.join(SRC, 'opsz-italic.css'), 'utf8')),
]

const rules: string[] = [
	'/* Generated by scripts/generate-fonts.ts. Do not edit by hand. */',
	`/* Newsreader, wght pinned to ${WEIGHT}, opsz left variable. */`,
]

for (const face of faces) {
	const source = await readFile(path.join(SRC, 'files', face.file))
	const pinned = await subsetFont(source, expand(face.unicodeRange), {
		targetFormat: 'woff2',
		variationAxes: { wght: WEIGHT },
	})
	const name = face.file.replace(/\.woff2$/, `-w${WEIGHT}.woff2`)
	await writeFile(path.join(OUT, name), pinned)
	rules.push(
		'',
		'@font-face {',
		'\tfont-family: \'Newsreader Variable\';',
		`\tfont-style: ${face.style};`,
		'\tfont-display: swap;',
		`\tfont-weight: ${WEIGHT};`,
		`\tsrc: url('./${name}') format('woff2');`,
		`\tunicode-range: ${face.unicodeRange};`,
		'}',
	)
	const kb = (n: number) => `${(n / 1024).toFixed(1)}K`
	console.log(`${name}: ${kb(source.byteLength)} → ${kb(pinned.byteLength)}`)
}

await writeFile(STYLESHEET, `${rules.join('\n')}\n`)
console.log(`wrote ${STYLESHEET}`)
