<script lang="ts">
	import { paintings, type Painting } from '$lib/site';
	import sizes from '$lib/painting-sizes.json';
	import { isPaintingWarm, paintingSrcset } from '$lib/painting-warm';

	type Props = {
		/** key in the paintings map */
		room: keyof typeof paintings | string;
		/** override or supply if not in the map */
		painting?: Painting;
		priority?: boolean;
		/** image only — no figure, caption, or reveal (for hero backgrounds) */
		bare?: boolean;
	};

	let { room, painting, priority = false, bare = false }: Props = $props();

	const p = $derived(painting ?? paintings[room as keyof typeof paintings]);
	const src = $derived(`/paintings/${p.key}`);

	// Responsive variants generated by scripts/generate-painting-sizes.ts.
	// The manifest carries the TRUE widths on disk, so descriptors are honest
	// (paintingSrcset is shared with the warmer, so a warmed canvas is the
	// same cache entry this component renders).
	const entry = $derived(sizes[p.key as keyof typeof sizes]);
	const srcsetFor = (ext: 'avif' | 'webp') => paintingSrcset(p.key, ext);
	// Heroes span the full viewport width.
	const sizesAttr = '100vw';

	// A canvas warmed before the navigation paints on the first frame; one
	// arriving later develops in via .loaded (see app.css). onload covers
	// the fetch, the action covers images already complete at mount.
	let loadFired = $state(false);
	const loaded = $derived(loadFired || isPaintingWarm(p.key));

	function markLoaded(img: HTMLImageElement) {
		if (img.complete && img.naturalWidth > 0) loadFired = true;
	}
</script>

{#snippet pic()}
	<picture>
		<source type="image/avif" srcset={srcsetFor('avif')} sizes={sizesAttr} />
		<source type="image/webp" srcset={srcsetFor('webp')} sizes={sizesAttr} />
		<img
			src={`${src}.webp`}
			alt={p.alt}
			width={entry?.width}
			height={entry?.height}
			loading={priority ? 'eager' : 'lazy'}
			fetchpriority={priority ? 'high' : 'auto'}
			decoding="async"
			class:loaded
			onload={() => (loadFired = true)}
			use:markLoaded
		/>
	</picture>
{/snippet}

<svelte:head>
	{#if priority && entry}
		<!-- Start the LCP fetch before layout: the hero painting is the largest
		     element on every page. -->
		<link
			rel="preload"
			as="image"
			type="image/avif"
			imagesrcset={srcsetFor('avif')}
			imagesizes={sizesAttr}
			fetchpriority="high"
		/>
	{/if}
</svelte:head>

{#if bare}
	<div class="frontispiece">
		{@render pic()}
	</div>
{:else}
	<figure class="rise">
		<div class="frontispiece">
			{@render pic()}
		</div>

		<figcaption class="plate mx-auto mt-4 px-6 rise-2">
			<em>{p.title}</em>
			<span class="plate-sep">·</span>
			{p.artist}
			<span class="plate-sep">·</span>
			{p.year}
			<span class="plate-sep">·</span>
			<a href={p.museumUrl} target="_blank" rel="noopener noreferrer" class="link-quiet"
				>{p.museum}</a
			>
		</figcaption>
	</figure>
{/if}
