<script lang="ts">
	import { paintings, type Painting } from '$lib/site';
	import sizes from '$lib/painting-sizes.json';

	type Props = {
		/** key in the paintings map */
		room: keyof typeof paintings | string;
		/** override or supply if not in the map */
		painting?: Painting;
		priority?: boolean;
		/** image only — no figure, caption, or reveal (for hero backgrounds) */
		bare?: boolean;
	};

	let { room, painting, priority = false, bare = false }: Props = $props();

	const p = $derived(painting ?? paintings[room as keyof typeof paintings]);
	const src = $derived(`/paintings/${p.key}`);

	// Responsive variants generated by scripts/generate-painting-sizes.ts.
	// The manifest carries the TRUE widths on disk, so descriptors are honest.
	const entry = $derived(sizes[p.key as keyof typeof sizes]);
	const srcsetFor = $derived((ext: 'avif' | 'webp') =>
		entry
			? entry.widths
					.map((w) => `${w === entry.width ? src : `${src}-${w}`}.${ext} ${w}w`)
					.join(', ')
			: `${src}.${ext}`
	);
	// Heroes span the full viewport width.
	const sizesAttr = '100vw';
</script>

{#snippet pic()}
	<picture>
		<source type="image/avif" srcset={srcsetFor('avif')} sizes={sizesAttr} />
		<source type="image/webp" srcset={srcsetFor('webp')} sizes={sizesAttr} />
		<img
			src={`${src}.webp`}
			alt={p.alt}
			width={entry?.width}
			height={entry?.height}
			loading={priority ? 'eager' : 'lazy'}
			fetchpriority={priority ? 'high' : 'auto'}
			decoding="async"
		/>
	</picture>
{/snippet}

<svelte:head>
	{#if priority && entry}
		<!-- Start the LCP fetch before layout: the hero painting is the largest
		     element on every page. -->
		<link
			rel="preload"
			as="image"
			type="image/avif"
			imagesrcset={srcsetFor('avif')}
			imagesizes={sizesAttr}
			fetchpriority="high"
		/>
	{/if}
</svelte:head>

{#if bare}
	<div class="frontispiece">
		{@render pic()}
	</div>
{:else}
	<figure class="rise">
		<div class="frontispiece">
			{@render pic()}
		</div>

		<figcaption class="plate mx-auto mt-4 px-6 rise-2">
			<em>{p.title}</em>
			<span class="plate-sep">·</span>
			{p.artist}
			<span class="plate-sep">·</span>
			{p.year}
			<span class="plate-sep">·</span>
			<a href={p.museumUrl} target="_blank" rel="noopener noreferrer" class="link-quiet"
				>{p.museum}</a
			>
		</figcaption>
	</figure>
{/if}
